import { randomUUID } from 'node:crypto';
import postgres from 'postgres';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { AuthService } from '../src/auth/service.js';
import { buildApp } from '../src/app.js';

const authUrl=process.env.AUTH_DATABASE_URL??'postgresql://vetoros_auth:local_auth_only@127.0.0.1:5432/vetoros';
const runtimeUrl=process.env.DATABASE_URL??'postgresql://vetoros_runtime:local_runtime_only@127.0.0.1:5432/vetoros';
const migrationUrl=process.env.MIGRATION_DATABASE_URL??'postgresql://vetoros_migration:local_migration_only@127.0.0.1:5432/vetoros';
const password=process.env.DEV_SEED_PASSWORD??'change-me-local-only';
const alpha='01992ea1-1250-7000-8000-000000000010',beta='01992ea1-1250-7000-8000-000000000020',companyAlpha='01992ea1-1250-7000-8000-000000000012',companyAlphaServices='01992ea1-1250-7000-8000-000000000017';
const service=new AuthService(authUrl,runtimeUrl,3600),app=buildApp({authService:service,loginRateLimitMax:100}),admin=postgres(migrationUrl);let cookie='';
const cookieFrom=(response:Awaited<ReturnType<typeof app.inject>>)=>String(response.headers['set-cookie']).split(';')[0]!;
const create=(payload:Record<string,unknown>)=>app.inject({method:'POST',url:'/customers',headers:{cookie},payload});
const uniqueCpf=()=>{const seed=randomUUID().replace(/\D/g,'').slice(0,9).padEnd(9,'7');const digits=seed.split('').map(Number);for(const size of [9,10]){const sum=digits.slice(0,size).reduce((total,digit,index)=>total+digit*(size+1-index),0);digits.push(((sum*10)%11)%10);}return digits.join('');};
const uniqueCnpj=()=>{const digits=randomUUID().replace(/\D/g,'').slice(0,8).padEnd(8,'3').split('').map(Number).concat([0,0,0,1,0,0]);for(const size of [12,13]){const weights=size===12?[5,4,3,2,9,8,7,6,5,4,3,2]:[6,5,4,3,2,9,8,7,6,5,4,3,2];const sum=weights.reduce((total,weight,index)=>total+digits[index]! * weight,0);const rest=sum%11;digits[size]=rest<2?0:11-rest;}return digits.join('');};

beforeAll(async()=>{await app.ready();const login=await app.inject({method:'POST',url:'/auth/login',payload:{email:'single@vetoros.local',password}});cookie=cookieFrom(login);});
afterAll(async()=>{await app.close();await service.close();await admin.end();});

describe('CUSTOMERS-01 API and PostgreSQL policies',()=>{
  it('creates PF, normalizes CPF and stores a separate address',async()=>{const cpf=uniqueCpf();const response=await create({personType:'individual',legalName:`PF ${randomUUID()}`,document:cpf,mobile:'(11) 99999-0000',whatsapp:'(11) 98888-0000',address:{postalCode:'01310-100',street:'Avenida Paulista',number:'1000',city:'São Paulo',state:'SP'}});expect(response.statusCode).toBe(201);const body=response.json() as {id:string;document_normalized:string;customer_number:number};expect(body.document_normalized).toBe(cpf);expect(body.customer_number).toBeGreaterThan(0);const detail=await app.inject({method:'GET',url:`/customers/${body.id}`,headers:{cookie}});expect(detail.statusCode).toBe(200);expect(detail.json()).toMatchObject({street:'Avenida Paulista',postal_code:'01310100'});});
  it('creates PJ and normalizes CNPJ',async()=>{const cnpj=uniqueCnpj();const response=await create({personType:'company',legalName:`PJ ${randomUUID()}`,tradeName:'Oficina Teste',document:cnpj});expect(response.statusCode).toBe(201);expect(response.json()).toMatchObject({document_type:'cnpj',document_normalized:cnpj});});
  it('allows a customer without document',async()=>expect((await create({personType:'individual',legalName:`Sem documento ${randomUUID()}`})).statusCode).toBe(201));
  it('rejects duplicate CPF in one tenant but allows it in another',async()=>{const cpf=uniqueCpf();expect((await create({personType:'individual',legalName:`Primeiro ${randomUUID()}`,document:cpf})).statusCode).toBe(201);expect((await create({personType:'individual',legalName:`Duplicado ${randomUUID()}`,document:cpf})).statusCode).toBe(409);await admin.begin(async tx=>{await tx`select set_config('app.tenant_id',${beta},true)`;const[number]=await tx<{last_number:number}[]>`insert into customer_number_counters(tenant_id,last_number) values(${beta},1) on conflict(tenant_id) do update set last_number=customer_number_counters.last_number+1 returning last_number`;await tx`insert into customers(tenant_id,customer_number,person_type,legal_name,document_type,document_normalized) values(${beta},${number!.last_number},'individual','Mesmo CPF no Beta','cpf',${cpf})`;});});
  it('keeps a known cross-tenant UUID invisible through API and RLS',async()=>{const id=randomUUID();await admin.begin(async tx=>{await tx`select set_config('app.tenant_id',${beta},true)`;const[number]=await tx<{last_number:number}[]>`insert into customer_number_counters(tenant_id,last_number) values(${beta},1) on conflict(tenant_id) do update set last_number=customer_number_counters.last_number+1 returning last_number`;await tx`insert into customers(id,tenant_id,customer_number,person_type,legal_name) values(${id},${beta},${number!.last_number},'individual','Oculto')`;});expect((await app.inject({method:'GET',url:`/customers/${id}`,headers:{cookie}})).statusCode).toBe(404);const runtime=postgres(runtimeUrl);try{const rows=await runtime.begin(async tx=>{await tx`select set_config('app.tenant_id',${alpha},true)`;return tx`select id from customers where id=${id}`;});expect(rows).toHaveLength(0);}finally{await runtime.end();}});
  it('generates unique sequential customer numbers under concurrency',async()=>{const responses=await Promise.all(Array.from({length:12},(_,i)=>create({personType:'individual',legalName:`Concorrente ${i} ${randomUUID()}`})));expect(responses.every(r=>r.statusCode===201)).toBe(true);const numbers=responses.map(r=>(r.json() as {customer_number:number}).customer_number);expect(new Set(numbers).size).toBe(numbers.length);const sorted=[...numbers].sort((a,b)=>a-b);expect(sorted.at(-1)!-sorted[0]!).toBe(numbers.length-1);});
  it('lists, paginates and searches by prefix',async()=>{const marker=`Busca${randomUUID().slice(0,8)}`;await create({personType:'individual',legalName:marker});const response=await app.inject({method:'GET',url:`/customers?search=${marker.slice(0,8)}&page=1&pageSize=5`,headers:{cookie}});expect(response.statusCode).toBe(200);const body=response.json() as {items:Array<{legal_name:string}>;page:number;pageSize:number};expect(body.items.some(row=>row.legal_name===marker)).toBe(true);expect(body).toMatchObject({page:1,pageSize:5});});
  it('updates fields and emits minimal append-only audit events',async()=>{const created=await create({personType:'individual',legalName:`Auditoria ${randomUUID()}`});const id=(created.json() as {id:string}).id;expect((await app.inject({method:'PATCH',url:`/customers/${id}`,headers:{cookie},payload:{legalName:'Nome atualizado'}})).statusCode).toBe(200);expect((await app.inject({method:'PATCH',url:`/customers/${id}`,headers:{cookie},payload:{status:'inactive'}})).statusCode).toBe(200);const events=await admin.begin(async tx=>{await tx`select set_config('app.tenant_id',${alpha},true)`;return tx<{action:string;metadata:Record<string,unknown>}[]>`select action,metadata from audit_events where resource_id=${id} order by created_at`;});expect(events.map(e=>e.action)).toEqual(['customer.created','customer.updated','customer.status_changed']);expect(JSON.stringify(events)).not.toContain('Nome atualizado');});
  it('rejects invalid documents and administrative fields',async()=>{expect((await create({personType:'individual',legalName:'Inválido',document:'123'})).statusCode).toBe(400);expect((await create({personType:'individual',legalName:'Ataque',tenantId:beta})).statusCode).toBe(400);});
  it('denies missing permission, inadequate scope and suspended membership',async()=>{const login=await service.login('shared@vetoros.local',password,{});const session=await service.selectTenant(login!.session,alpha);expect(session).toBeTruthy();expect(await service.hasPermission(session!,'customers.read',{requireTenant:true})).toBe(false);const role=randomUUID(),grant=randomUUID();await admin.begin(async tx=>{await tx`select set_config('app.tenant_id',${alpha},true)`;await tx`insert into tenant_roles(id,tenant_id,code,name,scope_type) values(${role},${alpha},${`customers-${role}`},'Customer scoped','company')`;await tx`insert into tenant_role_permissions(tenant_id,role_id,permission_id) select ${alpha},${role},id from permissions where code='customers.read'`;await tx`insert into access_grants(id,tenant_id,user_profile_id,role_id,scope_type,company_id) values(${grant},${alpha},${session!.activeUserProfileId},${role},'company',${companyAlpha})`;});expect(await service.hasPermission(session!,'customers.read',{companyId:companyAlpha})).toBe(true);expect(await service.hasPermission(session!,'customers.read',{companyId:companyAlphaServices})).toBe(false);await admin.begin(async tx=>{await tx`select set_config('app.tenant_id',${alpha},true)`;await tx`update tenant_memberships set status='suspended' where id=${session!.activeMembershipId}`;});expect(await service.hasPermission(session!,'customers.read',{companyId:companyAlpha})).toBe(false);await admin.begin(async tx=>{await tx`select set_config('app.tenant_id',${alpha},true)`;await tx`update tenant_memberships set status='active' where id=${session!.activeMembershipId}`;});});
});
