import { randomUUID } from 'node:crypto';import { afterAll,beforeAll,describe,expect,it } from 'vitest';import { AuthService } from '../src/auth/service.js';import { buildApp } from '../src/app.js';
const password=process.env.DEV_SEED_PASSWORD??'change-me-local-only',service=new AuthService(process.env.AUTH_DATABASE_URL??'postgresql://vetoros_auth:local_auth_only@127.0.0.1:5432/vetoros',process.env.DATABASE_URL??'postgresql://vetoros_runtime:local_runtime_only@127.0.0.1:5432/vetoros',3600),app=buildApp({authService:service,loginRateLimitMax:100});let cookie='';
beforeAll(async()=>{await app.ready();const r=await app.inject({method:'POST',url:'/auth/login',payload:{email:'single@vetoros.local',password}});cookie=String(r.headers['set-cookie']).split(';')[0]!;await app.inject({method:'POST',url:'/auth/operational-context',headers:{cookie},payload:{companyId:'01992ea1-1250-7000-8000-000000000012',branchId:'01992ea1-1250-7000-8000-000000000013'}});});afterAll(async()=>{await app.close();await service.close();});
const create=(overrides:Record<string,unknown>={})=>app.inject({method:'POST',url:'/inventory/parts',headers:{cookie},payload:{sku:`SKU-${randomUUID()}`,description:'Peça EST-01',unit:'un',referenceCost:10.5,referencePrice:20,...overrides}});const move=(partId:string,type:string,quantity:number,reason='Teste')=>app.inject({method:'POST',url:'/inventory/movements',headers:{cookie},payload:{partId,type,quantity,reason}});
describe('EST-01 inventory API',()=>{
 it('requires authentication and operational context',async()=>{expect((await app.inject({method:'GET',url:'/inventory/parts'})).statusCode).toBe(401);const login=await app.inject({method:'POST',url:'/auth/login',payload:{email:'shared@vetoros.local',password}});expect((await app.inject({method:'GET',url:'/inventory/parts',headers:{cookie:String(login.headers['set-cookie']).split(';')[0]!}})).statusCode).toBe(409);});
 it('creates, lists, searches, reads and updates a part while protecting ownership',async()=>{const made=await create(),partId=made.json().id;expect(made.statusCode).toBe(201);expect((await create({sku:made.json().sku})).statusCode).toBe(409);expect((await create({tenantId:randomUUID()})).statusCode).toBe(400);expect((await app.inject({method:'GET',url:`/inventory/parts?search=${made.json().sku}&status=active`,headers:{cookie}})).json().total).toBeGreaterThan(0);expect((await app.inject({method:'GET',url:`/inventory/parts/${partId}`,headers:{cookie}})).statusCode).toBe(200);expect((await app.inject({method:'PATCH',url:`/inventory/parts/${partId}`,headers:{cookie},payload:{description:'Peça atualizada',status:'inactive'}})).statusCode).toBe(200);});
 it('rejects invalid part payload, part and branch',async()=>{expect((await create({sku:'',referenceCost:-1})).statusCode).toBe(400);expect((await move(randomUUID(),'entry',1)).statusCode).toBe(404);const partId=(await create()).json().id;expect((await app.inject({method:'POST',url:'/inventory/movements',headers:{cookie},payload:{partId,type:'entry',quantity:1,reason:'x',branchId:randomUUID()}})).statusCode).toBe(400);});
 it('handles entries, exits, adjustments, balances and history',async()=>{const partId=(await create()).json().id;expect((await move(partId,'entry',10)).statusCode).toBe(201);expect((await move(partId,'exit',2.5)).statusCode).toBe(201);expect((await move(partId,'adjustment_in',1)).statusCode).toBe(201);expect((await move(partId,'adjustment_out',.5)).statusCode).toBe(201);const detail=(await app.inject({method:'GET',url:`/inventory/parts/${partId}`,headers:{cookie}})).json();expect(Number(detail.balance)).toBe(8);const history=(await app.inject({method:'GET',url:`/inventory/movements?partId=${partId}&type=exit`,headers:{cookie}})).json();expect(history.total).toBe(1);const balances=(await app.inject({method:'GET',url:`/inventory/balances?partId=${partId}`,headers:{cookie}})).json();expect(Number(balances[0].quantity)).toBe(8);});
 it('prevents negative stock and serializes concurrent exits',async()=>{const partId=(await create()).json().id;await move(partId,'entry',5);expect((await move(partId,'exit',6)).statusCode).toBe(409);const results=await Promise.all([move(partId,'exit',4),move(partId,'exit',4)]);expect(results.filter(r=>r.statusCode===201)).toHaveLength(1);expect(results.filter(r=>r.statusCode===409)).toHaveLength(1);const detail=(await app.inject({method:'GET',url:`/inventory/parts/${partId}`,headers:{cookie}})).json();expect(Number(detail.balance)).toBe(1);});
 it('does not couple quote or OS snapshots to stock',async()=>{const partId=(await create()).json().id;await move(partId,'entry',3);const quote=await app.inject({method:'POST',url:'/quotes',headers:{cookie},payload:{customerId:'01992ea1-1250-7000-8000-000000000050',title:'Sem estoque automático'}}),quoteId=quote.json().id;await app.inject({method:'POST',url:`/quotes/${quoteId}/items`,headers:{cookie},payload:{type:'part',description:'Snapshot sem vínculo',quantity:2,unitPrice:1}});await app.inject({method:'PATCH',url:`/quotes/${quoteId}`,headers:{cookie},payload:{status:'sent'}});await app.inject({method:'PATCH',url:`/quotes/${quoteId}`,headers:{cookie},payload:{status:'approved'}});await app.inject({method:'POST',url:`/quotes/${quoteId}/convert`,headers:{cookie}});const detail=(await app.inject({method:'GET',url:`/inventory/parts/${partId}`,headers:{cookie}})).json();expect(Number(detail.balance)).toBe(3);});
});
