import { randomUUID } from 'node:crypto'; import { afterAll,beforeAll,describe,expect,it } from 'vitest'; import { AuthService } from '../src/auth/service.js'; import { buildApp } from '../src/app.js';
const password=process.env.DEV_SEED_PASSWORD??'change-me-local-only',customer='01992ea1-1250-7000-8000-000000000050';const service=new AuthService(process.env.AUTH_DATABASE_URL??'postgresql://vetoros_auth:local_auth_only@127.0.0.1:5432/vetoros',process.env.DATABASE_URL??'postgresql://vetoros_runtime:local_runtime_only@127.0.0.1:5432/vetoros',3600),app=buildApp({authService:service,loginRateLimitMax:100});let cookie='';
beforeAll(async()=>{await app.ready();const login=await app.inject({method:'POST',url:'/auth/login',payload:{email:'single@vetoros.local',password}});cookie=String(login.headers['set-cookie']).split(';')[0]!;await app.inject({method:'POST',url:'/auth/operational-context',headers:{cookie},payload:{companyId:'01992ea1-1250-7000-8000-000000000012',branchId:'01992ea1-1250-7000-8000-000000000013'}});});afterAll(async()=>{await app.close();await service.close();});
const create=(overrides:Record<string,unknown>={})=>app.inject({method:'POST',url:'/quotes',headers:{cookie},payload:{customerId:customer,title:'Orçamento CRM-03',validUntil:'2026-12-31',...overrides}});
describe('CRM-03 quotes API',()=>{
 it('requires authentication and operational context',async()=>{expect((await app.inject({method:'GET',url:'/quotes'})).statusCode).toBe(401);const login=await app.inject({method:'POST',url:'/auth/login',payload:{email:'shared@vetoros.local',password}});const unselected=String(login.headers['set-cookie']).split(';')[0]!;expect((await app.inject({method:'GET',url:'/quotes',headers:{cookie:unselected}})).statusCode).toBe(409);});
 it('validates payload, customer and asset ownership',async()=>{expect((await create({title:'',tenantId:randomUUID()})).statusCode).toBe(400);expect((await create({customerId:randomUUID()})).statusCode).toBe(404);expect((await create({customerAssetId:randomUUID()})).statusCode).toBe(400);});
 it('generates unique sequential numbers under concurrency',async()=>{const responses=await Promise.all(Array.from({length:8},(_,i)=>create({title:`Quote concurrent ${i}`})));expect(responses.every(r=>r.statusCode===201)).toBe(true);const numbers=responses.map(r=>Number(r.json().quote_number));expect(new Set(numbers).size).toBe(numbers.length);});
 it('lists, searches, filters, reads and protects immutable fields',async()=>{const made=await create({title:'Busca exclusiva CRM03'}),quoteId=made.json().id;expect((await app.inject({method:'GET',url:'/quotes?search=Busca%20exclusiva&status=draft&order=number_desc',headers:{cookie}})).json().total).toBeGreaterThan(0);expect((await app.inject({method:'GET',url:`/quotes/${quoteId}`,headers:{cookie}})).statusCode).toBe(200);expect((await app.inject({method:'PATCH',url:`/quotes/${quoteId}`,headers:{cookie},payload:{customerId:randomUUID()}})).statusCode).toBe(400);});
 it('creates, updates and deletes items with deterministic totals',async()=>{const quoteId=(await create()).json().id;const made=await app.inject({method:'POST',url:`/quotes/${quoteId}/items`,headers:{cookie},payload:{type:'service',description:'Diagnóstico',quantity:2.5,unitPrice:100.10,discountAmount:10.05}});expect(made.statusCode).toBe(201);const itemId=made.json().id;let detail=(await app.inject({method:'GET',url:`/quotes/${quoteId}`,headers:{cookie}})).json();expect(Number(detail.total)).toBe(240.2);expect(Number(detail.discounts)).toBe(10.05);expect((await app.inject({method:'PATCH',url:`/quotes/${quoteId}/items/${itemId}`,headers:{cookie},payload:{discountAmount:500}})).statusCode).toBe(400);expect((await app.inject({method:'PATCH',url:`/quotes/${quoteId}/items/${itemId}`,headers:{cookie},payload:{description:'Diagnóstico completo'}})).statusCode).toBe(200);expect((await app.inject({method:'DELETE',url:`/quotes/${quoteId}/items/${itemId}`,headers:{cookie}})).statusCode).toBe(200);detail=(await app.inject({method:'GET',url:`/quotes/${quoteId}`,headers:{cookie}})).json();expect(detail.items).toHaveLength(0);});
 it('validates status transitions and converts approved quote once with item snapshot',async()=>{const quoteId=(await create({title:'Converter em OS'})).json().id;await app.inject({method:'POST',url:`/quotes/${quoteId}/items`,headers:{cookie},payload:{type:'part',description:'Peça snapshot',quantity:2,unitPrice:25,discountAmount:5}});expect((await app.inject({method:'PATCH',url:`/quotes/${quoteId}`,headers:{cookie},payload:{status:'approved'}})).statusCode).toBe(409);expect((await app.inject({method:'POST',url:`/quotes/${quoteId}/convert`,headers:{cookie}})).statusCode).toBe(409);expect((await app.inject({method:'PATCH',url:`/quotes/${quoteId}`,headers:{cookie},payload:{status:'sent'}})).statusCode).toBe(200);expect((await app.inject({method:'PATCH',url:`/quotes/${quoteId}`,headers:{cookie},payload:{status:'approved'}})).statusCode).toBe(200);const converted=await app.inject({method:'POST',url:`/quotes/${quoteId}/convert`,headers:{cookie}});expect(converted.statusCode).toBe(201);const orderId=converted.json().id;const order=(await app.inject({method:'GET',url:`/service-orders/${orderId}`,headers:{cookie}})).json();expect(order.items).toHaveLength(1);expect(order.items[0].description).toBe('Peça snapshot');const again=await app.inject({method:'POST',url:`/quotes/${quoteId}/convert`,headers:{cookie}});expect(again.statusCode).toBe(200);expect(again.json().id).toBe(orderId);});
});
