import { afterAll,beforeAll,describe,expect,it } from 'vitest';
import { AuthService } from '../src/auth/service.js'; import { buildApp } from '../src/app.js';
const password=process.env.DEV_SEED_PASSWORD??'change-me-local-only'; const customer='01992ea1-1250-7000-8000-000000000050';
const service=new AuthService(process.env.AUTH_DATABASE_URL??'postgresql://vetoros_auth:local_auth_only@127.0.0.1:5432/vetoros',process.env.DATABASE_URL??'postgresql://vetoros_runtime:local_runtime_only@127.0.0.1:5432/vetoros',3600); const app=buildApp({authService:service,loginRateLimitMax:100}); let cookie='';
beforeAll(async()=>{await app.ready();const r=await app.inject({method:'POST',url:'/auth/login',payload:{email:'single@vetoros.local',password}});cookie=String(r.headers['set-cookie']).split(';')[0]!;await app.inject({method:'POST',url:'/auth/operational-context',headers:{cookie},payload:{companyId:'01992ea1-1250-7000-8000-000000000012',branchId:'01992ea1-1250-7000-8000-000000000013'}});}); afterAll(async()=>{await app.close();await service.close();});
const create=(payload:Record<string,unknown>)=>app.inject({method:'POST',url:'/service-orders',headers:{cookie},payload});
describe('OS-01 dedicated API suite',()=>{
 it('creates with operational context and without asset',async()=>{const r=await create({customerId:customer,title:'OS test',reportedProblem:'Falha'});expect(r.statusCode).toBe(201);expect(Number((r.json() as {order_number:number|string}).order_number)).toBeGreaterThan(0);});
 it('rejects invalid customer and invalid payload',async()=>{expect((await create({customerId:'01992ea1-1250-7000-8000-000000000022',title:'x',reportedProblem:'x'})).statusCode).toBe(404);expect((await create({customerId:customer,title:''})).statusCode).toBe(400);});
 it('generates unique numbers under concurrency',async()=>{const rs=await Promise.all(Array.from({length:10},(_,i)=>create({customerId:customer,title:`Concurrent ${i}`,reportedProblem:'x'})));expect(rs.every(r=>r.statusCode===201)).toBe(true);const nums=rs.map(r=>(r.json() as {order_number:number}).order_number);expect(new Set(nums).size).toBe(nums.length);});
 it('lists, filters, reads and updates',async()=>{const r=await create({customerId:customer,title:'Status test',reportedProblem:'x'});const id=(r.json() as {id:string}).id;expect((await app.inject({method:'GET',url:'/service-orders?status=open',headers:{cookie}})).statusCode).toBe(200);expect((await app.inject({method:'GET',url:`/service-orders/${id}`,headers:{cookie}})).statusCode).toBe(200);expect((await app.inject({method:'PATCH',url:`/service-orders/${id}`,headers:{cookie},payload:{status:'in_progress'}})).statusCode).toBe(200);});
 it('rejects asset/customer mismatch and immutable ownership fields',async()=>{expect((await create({customerId:customer,assetId:'01992ea1-1250-7000-8000-000000000051',title:'x',reportedProblem:'x'})).statusCode).toBe(400);const r=await create({customerId:customer,title:'x',reportedProblem:'x'});const id=(r.json() as {id:string}).id;expect((await app.inject({method:'PATCH',url:`/service-orders/${id}`,headers:{cookie},payload:{customerId:'01992ea1-1250-7000-8000-000000000022'}})).statusCode).toBe(400);});
});
