import{randomUUID}from'node:crypto';import{afterAll,beforeAll,describe,expect,it}from'vitest';import{AuthService}from'../src/auth/service.js';import{buildApp}from'../src/app.js';
const password=process.env.DEV_SEED_PASSWORD??'change-me-local-only',service=new AuthService(process.env.AUTH_DATABASE_URL??'postgresql://vetoros_auth:local_auth_only@127.0.0.1:5432/vetoros',process.env.DATABASE_URL??'postgresql://vetoros_runtime:local_runtime_only@127.0.0.1:5432/vetoros',3600),app=buildApp({authService:service,loginRateLimitMax:100});let cookie='';beforeAll(async()=>{await app.ready();const r=await app.inject({method:'POST',url:'/auth/login',payload:{email:'single@vetoros.local',password}});cookie=String(r.headers['set-cookie']).split(';')[0]!;});afterAll(async()=>{await app.close();await service.close();});
const create=(overrides:Record<string,unknown>={})=>app.inject({method:'POST',url:'/suppliers',headers:{cookie},payload:{personType:'company',legalName:`Fornecedor ${randomUUID()}`,tradeName:'Parceiro',...overrides}});
describe('COM-01 suppliers API',()=>{
 it('requires authentication and tenant context',async()=>{expect((await app.inject({method:'POST',url:'/suppliers',payload:{personType:'company',legalName:'x'}})).statusCode).toBe(401);const login=await app.inject({method:'POST',url:'/auth/login',payload:{email:'shared@vetoros.local',password}});expect((await app.inject({method:'POST',url:'/suppliers',headers:{cookie:String(login.headers['set-cookie']).split(';')[0]!},payload:{personType:'company',legalName:'x'}})).statusCode).toBe(409);});
 it('creates valid PF and PJ and normalizes documents',async()=>{const pf=await create({personType:'individual',document:'529.982.247-25'}),pj=await create({document:'11.222.333/0001-81'});expect(pf.statusCode).toBe(201);expect(pf.json().document_normalized).toBe('52998224725');expect(pj.statusCode).toBe(201);expect(pj.json().document_normalized).toBe('11222333000181');});
 it('rejects invalid documents, invalid payload and duplicate documents',async()=>{expect((await create({personType:'individual',document:'111.111.111-11'})).statusCode).toBe(400);expect((await create({legalName:'',tenantId:randomUUID()})).statusCode).toBe(400);const doc='45.723.174/0001-10';const first=await create({document:doc});expect(first.statusCode).toBe(201);expect((await create({document:doc})).statusCode).toBe(409);});
 it('generates unique sequential numbers under concurrency',async()=>{const results=await Promise.all(Array.from({length:10},()=>create()));expect(results.every(r=>r.statusCode===201)).toBe(true);const numbers=results.map(r=>Number(r.json().supplier_number));expect(new Set(numbers).size).toBe(numbers.length);});
 it('lists, searches, paginates, filters, orders and reads detail',async()=>{const made=await create({legalName:'Fornecedor Busca COM01'}),id=made.json().id;const list=await app.inject({method:'GET',url:'/suppliers?search=Busca%20COM01&status=active&page=1&pageSize=5&order=name_asc',headers:{cookie}});expect(list.statusCode).toBe(200);expect(list.json().total).toBeGreaterThan(0);expect((await app.inject({method:'GET',url:`/suppliers/${id}`,headers:{cookie}})).statusCode).toBe(200);expect((await app.inject({method:'GET',url:`/suppliers/${randomUUID()}`,headers:{cookie}})).statusCode).toBe(404);});
 it('updates and activates/inactivates without allowing ownership fields',async()=>{const made=await create(),id=made.json().id;expect((await app.inject({method:'PATCH',url:`/suppliers/${id}`,headers:{cookie},payload:{legalName:'Fornecedor Atualizado',status:'inactive'}})).statusCode).toBe(200);expect((await app.inject({method:'PATCH',url:`/suppliers/${id}`,headers:{cookie},payload:{status:'active'}})).statusCode).toBe(200);expect((await app.inject({method:'PATCH',url:`/suppliers/${id}`,headers:{cookie},payload:{tenantId:randomUUID(),supplierNumber:1}})).statusCode).toBe(400);expect((await app.inject({method:'DELETE',url:`/suppliers/${id}`,headers:{cookie}})).statusCode).toBe(404);});
 it('creates, lists and updates multiple addresses with one primary',async()=>{const id=(await create()).json().id;const first=await app.inject({method:'POST',url:`/suppliers/${id}/addresses`,headers:{cookie},payload:{addressType:'commercial',postalCode:'01310-100',street:'Av Paulista',city:'São Paulo',state:'SP',isPrimary:true}});expect(first.statusCode).toBe(201);const second=await app.inject({method:'POST',url:`/suppliers/${id}/addresses`,headers:{cookie},payload:{addressType:'billing',street:'Rua B',city:'São Paulo',state:'SP',isPrimary:true}});expect(second.statusCode).toBe(201);expect((await app.inject({method:'PATCH',url:`/suppliers/${id}/addresses/${first.json().id}`,headers:{cookie},payload:{city:'Campinas'}})).statusCode).toBe(200);const rows=(await app.inject({method:'GET',url:`/suppliers/${id}/addresses`,headers:{cookie}})).json();expect(rows).toHaveLength(2);expect(rows.filter((a:{is_primary:boolean})=>a.is_primary)).toHaveLength(1);});
 it('creates, normalizes, lists and updates contacts by type',async()=>{const id=(await create()).json().id;const phone=await app.inject({method:'POST',url:`/suppliers/${id}/contacts`,headers:{cookie},payload:{contactType:'phone',value:'(11) 3333-4444',isPrimary:true}});expect(phone.statusCode).toBe(201);expect(phone.json().value_normalized).toBe('1133334444');const email=await app.inject({method:'POST',url:`/suppliers/${id}/contacts`,headers:{cookie},payload:{contactType:'email',value:'COMERCIAL@EXAMPLE.COM',isPrimary:true}});expect(email.statusCode).toBe(201);expect((await app.inject({method:'PATCH',url:`/suppliers/${id}/contacts/${email.json().id}`,headers:{cookie},payload:{value:'novo@example.com'}})).statusCode).toBe(200);expect((await app.inject({method:'GET',url:`/suppliers/${id}/contacts`,headers:{cookie}})).json()).toHaveLength(2);});
});
