// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import { sql } from 'drizzle-orm';
import { z } from 'zod';
import type { AuthService, AuthSession, ResourceScope } from '../auth/service.js';
import { requirePermission } from '../auth/service.js';
const id=z.string().uuid(); const params=z.object({id});
const createSchema=z.object({customerId:id,assetId:id.nullable().optional(),title:z.string().trim().min(1).max(200),reportedProblem:z.string().trim().min(1).max(4000),initialNotes:z.string().trim().max(4000).nullable().optional(),status:z.enum(['open','in_progress','completed','canceled']).default('open')}).strict();
const updateSchema=createSchema.omit({customerId:true}).partial().strict();
const listSchema=z.object({search:z.string().trim().max(100).optional(),customerId:id.optional(),status:z.enum(['open','in_progress','completed','canceled']).optional(),page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(20)}).strict();
const scope=(s:AuthSession):ResourceScope=>s.activeBranchId?{companyId:s.activeCompanyId!,branchId:s.activeBranchId}:s.activeCompanyId?{companyId:s.activeCompanyId}:{requireTenant:true};
export function registerServiceOrderRoutes(app:FastifyInstance,service:AuthService){
 async function auth(req:FastifyRequest,reply:FastifyReply){const s=await service.session(req.cookies.vetoros_session);if(!s){reply.code(401).send({error:'unauthorized'});return;}if(!s.activeTenantId||!s.activeCompanyId||!s.activeBranchId){reply.code(409).send({error:'operational_context_required'});return;}return s;}
 async function allow(reply:FastifyReply,s:AuthSession,p:string){try{await requirePermission(service,s,p,scope(s));return true;}catch{reply.code(403).send({error:'forbidden'});return false;}}
 app.get('/service-orders',async(req,reply)=>{const q=listSchema.safeParse(req.query);if(!q.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'service_orders.read'))return;const term=q.data.search?`${q.data.search}%`:null,offset=(q.data.page-1)*q.data.pageSize;const rows=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`select o.*,c.legal_name as customer_name,b.name as branch_name,a.internal_identifier as asset_identifier,count(*) over()::int as total from service_orders o join customers c on c.id=o.customer_id join branches b on b.id=o.branch_id left join customer_assets a on a.id=o.asset_id where (${q.data.customerId??null}::uuid is null or o.customer_id=${q.data.customerId??null}) and (${q.data.status??null}::text is null or o.status=${q.data.status??null}) and (${term}::text is null or o.order_number::text like ${term} or lower(c.legal_name) like lower(${term})) order by o.created_at desc limit ${q.data.pageSize} offset ${offset}`));return{items:rows.map(r=>Object.fromEntries(Object.entries(r).filter(([k])=>k!=='total'))),page:q.data.page,pageSize:q.data.pageSize,total:Number(rows[0]?.total??0)};});
 app.get('/service-orders/:id',async(req,reply)=>{const p=params.safeParse(req.params);if(!p.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'service_orders.read'))return;const result=await service.withAuthenticatedTenant(s,async tx=>{const [row]=await tx.execute(sql`select o.*,c.legal_name as customer_name,b.name as branch_name,co.legal_name as company_name,a.internal_identifier as asset_identifier from service_orders o join customers c on c.id=o.customer_id join branches b on b.id=o.branch_id left join companies co on co.id=o.company_id left join customer_assets a on a.id=o.asset_id where o.id=${p.data.id}`);if(!row)return null;const items=await tx.execute(sql`select * from service_order_items where service_order_id=${p.data.id} order by created_at`);const typedItems=items as Array<{total_amount:string|number;discount_amount:string|number}>;return {...row,items,subtotal:typedItems.reduce((n,i)=>n+Number(i.total_amount),0),discounts:typedItems.reduce((n,i)=>n+Number(i.discount_amount),0),total:typedItems.reduce((n,i)=>n+Number(i.total_amount),0)};});return result??reply.code(404).send({error:'not_found'});});
 app.post('/service-orders',async(req,reply)=>{const b=createSchema.safeParse(req.body);if(!b.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'service_orders.create'))return;const row=await service.withAuthenticatedTenant(s,async tx=>{const customer=await tx.execute(sql`select id from customers where id=${b.data.customerId}`);if(!customer.length)return null;if(b.data.assetId){const asset=await tx.execute(sql`select id from customer_assets where id=${b.data.assetId} and customer_id=${b.data.customerId}`);if(!asset.length)return 'asset_invalid';}const [counter]=await tx.execute<{last_number:number}>(sql`insert into service_order_number_counters(tenant_id,last_number) values(${s.activeTenantId!},1) on conflict(tenant_id) do update set last_number=service_order_number_counters.last_number+1,updated_at=now() returning last_number`);const [o]=await tx.execute(sql`insert into service_orders(tenant_id,company_id,branch_id,order_number,customer_id,asset_id,status,title,reported_problem,initial_notes,created_by_identity_id,updated_by_identity_id) values(${s.activeTenantId!},${s.activeCompanyId!},${s.activeBranchId!},${Number(counter!.last_number)},${b.data.customerId},${b.data.assetId??null},${b.data.status},${b.data.title},${b.data.reportedProblem},${b.data.initialNotes??null},${s.identityId},${s.identityId}) returning *`);return o!;});if(!row)return reply.code(404).send({error:'customer_not_found'});if(row==='asset_invalid')return reply.code(400).send({error:'asset_customer_mismatch'});await service.auditResource(s,'service_order.created','service_order',String((row as {id:string}).id));return reply.code(201).send(row);});
 app.patch('/service-orders/:id',async(req,reply)=>{const p=params.safeParse(req.params),b=updateSchema.safeParse(req.body);if(!p.success||!b.success||!Object.keys(b.data).length)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'service_orders.update'))return;if(b.data.status&&['completed','canceled'].includes(b.data.status)){const active=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`select 1 from service_order_item_stock_reservations where service_order_id=${p.data.id} and reserved_quantity>0 limit 1`));if(active.length)return reply.code(409).send({error:'active_stock_reservation'});}
 // FIN-01, seção 9: mesma regra aplicada a vendas (sales.ts) — uma OS com recebimento sem
 // estorno não pode ser cancelada silenciosamente. Só se aplica a `canceled` (concluir uma OS
 // com pagamento parcial já recebido é o fluxo normal da seção 7, não algo a bloquear).
 if(b.data.status==='canceled'){const activePayments=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`select 1 from payments p where p.service_order_id=${p.data.id} and not exists (select 1 from cash_movements m where m.payment_id=p.id and m.type='refund') limit 1`));if(activePayments.length)return reply.code(409).send({error:'service_order_has_active_payments'});}
 const [row]=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`update service_orders set asset_id=case when ${'assetId'in b.data} then ${b.data.assetId??null} else asset_id end,title=coalesce(${b.data.title??null},title),reported_problem=coalesce(${b.data.reportedProblem??null},reported_problem),initial_notes=case when ${'initialNotes'in b.data} then ${b.data.initialNotes??null} else initial_notes end,status=coalesce(${b.data.status??null},status),updated_by_identity_id=${s.identityId},updated_at=now() where id=${p.data.id} returning *`));if(!row)return reply.code(404).send({error:'not_found'});await service.auditResource(s,'service_order.updated','service_order',p.data.id,{status:b.data.status});return row;});
 app.get('/service-orders/:id/items',async(req,reply)=>{const p=params.safeParse(req.params);if(!p.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'service_orders.read'))return;return service.withAuthenticatedTenant(s,tx=>tx.execute(sql`select * from service_order_items where service_order_id=${p.data.id} order by created_at`));});
 app.post('/service-orders/:id/items',async(req,reply)=>{const p=params.safeParse(req.params),b=z.object({type:z.enum(['service','part']),inventoryPartId:id.nullable().optional(),description:z.string().trim().min(1).max(300),quantity:z.coerce.number().positive(),unitPrice:z.coerce.number().nonnegative(),discountAmount:z.coerce.number().nonnegative().default(0),notes:z.string().max(2000).nullable().optional()}).strict().safeParse(req.body);if(!p.success||!b.success||b.data.discountAmount>b.data.quantity*b.data.unitPrice||(b.data.type==='service'&&b.data.inventoryPartId))return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'service_orders.update'))return;const result=await service.withAuthenticatedTenant(s,async tx=>{const exists=await tx.execute(sql`select id from service_orders where id=${p.data.id}`);if(!exists.length)return 'order';if(b.data.inventoryPartId&&!await tx.execute(sql`select id from inventory_parts where id=${b.data.inventoryPartId} and status='active'`).then(r=>r.length))return 'part';const [row]=await tx.execute(sql`insert into service_order_items(tenant_id,service_order_id,type,inventory_part_id,description,quantity,unit_price,discount_amount,notes) values(${s.activeTenantId!},${p.data.id},${b.data.type},${b.data.inventoryPartId??null},${b.data.description},${b.data.quantity},${b.data.unitPrice},${b.data.discountAmount},${b.data.notes??null}) returning *`);return row;});if(result==='order')return reply.code(404).send({error:'not_found'});if(result==='part')return reply.code(404).send({error:'inventory_part_not_found'});await service.auditResource(s,'service_order_item.created','service_order',p.data.id,{inventoryPartId:b.data.inventoryPartId});return reply.code(201).send(result);});
 app.patch('/service-orders/:id/items/:itemId',async(req,reply)=>{const p=z.object({id,itemId:id}).safeParse(req.params),b=z.object({type:z.enum(['service','part']).optional(),inventoryPartId:id.nullable().optional(),description:z.string().trim().min(1).max(300).optional(),quantity:z.coerce.number().positive().optional(),unitPrice:z.coerce.number().nonnegative().optional(),discountAmount:z.coerce.number().nonnegative().optional(),notes:z.string().max(2000).nullable().optional()}).strict().safeParse(req.body);if(!p.success||!b.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'service_orders.update'))return;const [old]=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`select * from service_order_items where id=${p.data.itemId} and service_order_id=${p.data.id}`));if(!old)return reply.code(404).send({error:'not_found'});const history=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`select 1 from service_order_item_stock_reservations where service_order_item_id=${p.data.itemId}`));if(history.length&&('type'in b.data||'quantity'in b.data||'inventoryPartId'in b.data))return reply.code(409).send({error:'stock_history_locks_item'});const part='inventoryPartId'in b.data?b.data.inventoryPartId:old.inventory_part_id,type=b.data.type??old.type;if(type==='service'&&part)return reply.code(400).send({error:'invalid_request'});if(part){const found=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`select id from inventory_parts where id=${part}`));if(!found.length)return reply.code(404).send({error:'inventory_part_not_found'});}const q=b.data.quantity??Number(old.quantity),u=b.data.unitPrice??Number(old.unit_price),d=b.data.discountAmount??Number(old.discount_amount);if(d>q*u)return reply.code(400).send({error:'invalid_request'});const [row]=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`update service_order_items set type=${type},inventory_part_id=${part??null},description=coalesce(${b.data.description??null},description),quantity=${q},unit_price=${u},discount_amount=${d},notes=case when ${'notes'in b.data} then ${b.data.notes??null} else notes end,updated_at=now() where id=${p.data.itemId} and service_order_id=${p.data.id} returning *`));await service.auditResource(s,'service_order_item.updated','service_order',p.data.id,{inventoryPartId:part});return row;});
 app.delete('/service-orders/:id/items/:itemId',async(req,reply)=>{const p=z.object({id,itemId:id}).safeParse(req.params);if(!p.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'service_orders.update'))return;const history=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`select 1 from service_order_item_stock_reservations where service_order_item_id=${p.data.itemId}`));if(history.length)return reply.code(409).send({error:'stock_history_locks_item'});const [row]=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`delete from service_order_items where id=${p.data.itemId} and service_order_id=${p.data.id} returning id`));if(!row)return reply.code(404).send({error:'not_found'});await service.auditResource(s,'service_order_item.deleted','service_order',p.data.id);return {deleted:true};});
 const stockParams=z.object({id,itemId:id}),stockBody=z.object({quantity:z.coerce.number().positive(),idempotencyKey:z.string().trim().min(8).max(120)}).strict();
 app.get('/service-orders/:id/items/:itemId/stock',async(req,reply)=>{const p=stockParams.safeParse(req.params);if(!p.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'service_orders.read')||!await allow(reply,s,'inventory.read'))return;const [row]=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`select i.inventory_part_id,p.sku,p.description,o.branch_id,coalesce(b.quantity,0) physical_balance,coalesce((select sum(r.reserved_quantity) from service_order_item_stock_reservations r where r.branch_id=o.branch_id and r.inventory_part_id=i.inventory_part_id),0) total_reserved,coalesce(r.reserved_quantity,0) item_reserved,coalesce(r.consumed_quantity,0) consumed,coalesce(r.returned_quantity,0) returned,coalesce(r.status,'unreserved') status from service_order_items i join service_orders o on o.id=i.service_order_id left join inventory_parts p on p.id=i.inventory_part_id left join stock_balances b on b.branch_id=o.branch_id and b.part_id=i.inventory_part_id left join service_order_item_stock_reservations r on r.service_order_item_id=i.id where o.id=${p.data.id} and i.id=${p.data.itemId}`));if(!row)return reply.code(404).send({error:'not_found'});return{...row,available:Number(row.physical_balance)-Number(row.total_reserved)};});
 for(const action of ['reserve','release','consume','return'] as const)app.post(`/service-orders/:id/items/:itemId/stock/${action}`,async(req,reply)=>{const p=stockParams.safeParse(req.params),b=stockBody.safeParse(req.body);if(!p.success||!b.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'service_orders.update')||!await allow(reply,s,'inventory.move'))return;try{const [result]=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`select * from service_order_stock_action(${p.data.id},${p.data.itemId},${action},${b.data.quantity},${b.data.idempotencyKey})`));await service.auditResource(s,`service_order_stock.${action}`,'service_order',p.data.id,{itemId:p.data.itemId,quantity:b.data.quantity,idempotencyKey:b.data.idempotencyKey});return reply.code(result.idempotent?200:201).send(result);}catch(e){const code=(e as {code?:string;cause?:{code?:string}}).code??(e as {cause?:{code?:string}}).cause?.code;if(code==='23514')return reply.code(409).send({error:'insufficient_or_invalid_quantity'});if(code==='P0002')return reply.code(404).send({error:'not_found'});if(code==='22023')return reply.code(400).send({error:'invalid_stock_operation'});if(code==='55000')return reply.code(409).send({error:'service_order_state_forbids_stock'});if(code==='23505')return reply.code(409).send({error:'idempotency_conflict'});throw e;}});
}
