// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import { sql } from 'drizzle-orm';
import { z } from 'zod';
import type { AuthService, AuthSession, ResourceScope } from '../auth/service.js';
import { requirePermission } from '../auth/service.js';
const id=z.string().uuid(); const params=z.object({id});
const createSchema=z.object({customerId:id,assetId:id.nullable().optional(),title:z.string().trim().min(1).max(200),reportedProblem:z.string().trim().min(1).max(4000),initialNotes:z.string().trim().max(4000).nullable().optional(),status:z.enum(['open','in_progress','completed','canceled']).default('open')}).strict();
const updateSchema=createSchema.omit({customerId:true}).partial().strict();
const listSchema=z.object({search:z.string().trim().max(100).optional(),customerId:id.optional(),status:z.enum(['open','in_progress','completed','canceled']).optional(),page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(20)}).strict();
const scope=(s:AuthSession):ResourceScope=>s.activeBranchId?{companyId:s.activeCompanyId!,branchId:s.activeBranchId}:s.activeCompanyId?{companyId:s.activeCompanyId}:{requireTenant:true};
export function registerServiceOrderRoutes(app:FastifyInstance,service:AuthService){
 async function auth(req:FastifyRequest,reply:FastifyReply){const s=await service.session(req.cookies.vetoros_session);if(!s){reply.code(401).send({error:'unauthorized'});return;}if(!s.activeTenantId||!s.activeCompanyId||!s.activeBranchId){reply.code(409).send({error:'operational_context_required'});return;}return s;}
 async function allow(reply:FastifyReply,s:AuthSession,p:string){try{await requirePermission(service,s,p,scope(s));return true;}catch{reply.code(403).send({error:'forbidden'});return false;}}
 app.get('/service-orders',async(req,reply)=>{const q=listSchema.safeParse(req.query);if(!q.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'service_orders.read'))return;const term=q.data.search?`${q.data.search}%`:null,offset=(q.data.page-1)*q.data.pageSize;const rows=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`select o.*,c.legal_name as customer_name,b.name as branch_name,a.internal_identifier as asset_identifier,count(*) over()::int as total from service_orders o join customers c on c.id=o.customer_id join branches b on b.id=o.branch_id left join customer_assets a on a.id=o.asset_id where (${q.data.customerId??null}::uuid is null or o.customer_id=${q.data.customerId??null}) and (${q.data.status??null}::text is null or o.status=${q.data.status??null}) and (${term}::text is null or o.order_number::text like ${term} or lower(c.legal_name) like lower(${term})) order by o.created_at desc limit ${q.data.pageSize} offset ${offset}`));return{items:rows.map(r=>Object.fromEntries(Object.entries(r).filter(([k])=>k!=='total'))),page:q.data.page,pageSize:q.data.pageSize,total:Number(rows[0]?.total??0)};});
 app.get('/service-orders/:id',async(req,reply)=>{const p=params.safeParse(req.params);if(!p.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'service_orders.read'))return;const result=await service.withAuthenticatedTenant(s,async tx=>{const [row]=await tx.execute(sql`select o.*,c.legal_name as customer_name,b.name as branch_name,co.legal_name as company_name,a.internal_identifier as asset_identifier from service_orders o join customers c on c.id=o.customer_id join branches b on b.id=o.branch_id left join companies co on co.id=o.company_id left join customer_assets a on a.id=o.asset_id where o.id=${p.data.id}`);if(!row)return null;const items=await tx.execute(sql`select * from service_order_items where service_order_id=${p.data.id} order by created_at`);const typedItems=items as Array<{total_amount:string|number;discount_amount:string|number}>;return {...row,items,subtotal:typedItems.reduce((n,i)=>n+Number(i.total_amount),0),discounts:typedItems.reduce((n,i)=>n+Number(i.discount_amount),0),total:typedItems.reduce((n,i)=>n+Number(i.total_amount),0)};});return result??reply.code(404).send({error:'not_found'});});
 app.post('/service-orders',async(req,reply)=>{const b=createSchema.safeParse(req.body);if(!b.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'service_orders.create'))return;const row=await service.withAuthenticatedTenant(s,async tx=>{const customer=await tx.execute(sql`select id from customers where id=${b.data.customerId}`);if(!customer.length)return null;if(b.data.assetId){const asset=await tx.execute(sql`select id from customer_assets where id=${b.data.assetId} and customer_id=${b.data.customerId}`);if(!asset.length)return 'asset_invalid';}const [counter]=await tx.execute<{last_number:number}>(sql`insert into service_order_number_counters(tenant_id,last_number) values(${s.activeTenantId!},1) on conflict(tenant_id) do update set last_number=service_order_number_counters.last_number+1,updated_at=now() returning last_number`);const [o]=await tx.execute(sql`insert into service_orders(tenant_id,company_id,branch_id,order_number,customer_id,asset_id,status,title,reported_problem,initial_notes,created_by_identity_id,updated_by_identity_id) values(${s.activeTenantId!},${s.activeCompanyId!},${s.activeBranchId!},${Number(counter!.last_number)},${b.data.customerId},${b.data.assetId??null},${b.data.status},${b.data.title},${b.data.reportedProblem},${b.data.initialNotes??null},${s.identityId},${s.identityId}) returning *`);return o!;});if(!row)return reply.code(404).send({error:'customer_not_found'});if(row==='asset_invalid')return reply.code(400).send({error:'asset_customer_mismatch'});await service.auditResource(s,'service_order.created','service_order',String((row as {id:string}).id));return reply.code(201).send(row);});
 app.patch('/service-orders/:id',async(req,reply)=>{const p=params.safeParse(req.params),b=updateSchema.safeParse(req.body);if(!p.success||!b.success||!Object.keys(b.data).length)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'service_orders.update'))return;const [row]=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`update service_orders set asset_id=case when ${'assetId'in b.data} then ${b.data.assetId??null} else asset_id end,title=coalesce(${b.data.title??null},title),reported_problem=coalesce(${b.data.reportedProblem??null},reported_problem),initial_notes=case when ${'initialNotes'in b.data} then ${b.data.initialNotes??null} else initial_notes end,status=coalesce(${b.data.status??null},status),updated_by_identity_id=${s.identityId},updated_at=now() where id=${p.data.id} returning *`));if(!row)return reply.code(404).send({error:'not_found'});await service.auditResource(s,'service_order.updated','service_order',p.data.id,{status:b.data.status});return row;});
 app.get('/service-orders/:id/items',async(req,reply)=>{const p=params.safeParse(req.params);if(!p.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'service_orders.read'))return;return service.withAuthenticatedTenant(s,tx=>tx.execute(sql`select * from service_order_items where service_order_id=${p.data.id} order by created_at`));});
 app.post('/service-orders/:id/items',async(req,reply)=>{const p=params.safeParse(req.params),b=z.object({type:z.enum(['service','part']),description:z.string().trim().min(1).max(300),quantity:z.coerce.number().positive(),unitPrice:z.coerce.number().nonnegative(),discountAmount:z.coerce.number().nonnegative().default(0),notes:z.string().max(2000).nullable().optional()}).strict().safeParse(req.body);if(!p.success||!b.success||b.data.discountAmount>b.data.quantity*b.data.unitPrice)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'service_orders.update'))return;const exists=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`select id from service_orders where id=${p.data.id}`));if(!exists.length)return reply.code(404).send({error:'not_found'});const [row]=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`insert into service_order_items(tenant_id,service_order_id,type,description,quantity,unit_price,discount_amount,notes) values(${s.activeTenantId!},${p.data.id},${b.data.type},${b.data.description},${b.data.quantity},${b.data.unitPrice},${b.data.discountAmount},${b.data.notes??null}) returning *`));await service.auditResource(s,'service_order_item.created','service_order',p.data.id);return reply.code(201).send(row);});
 app.patch('/service-orders/:id/items/:itemId',async(req,reply)=>{const p=z.object({id,itemId:id}).safeParse(req.params),b=z.object({type:z.enum(['service','part']).optional(),description:z.string().trim().min(1).max(300).optional(),quantity:z.coerce.number().positive().optional(),unitPrice:z.coerce.number().nonnegative().optional(),discountAmount:z.coerce.number().nonnegative().optional(),notes:z.string().max(2000).nullable().optional()}).strict().safeParse(req.body);if(!p.success||!b.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'service_orders.update'))return;const [old]=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`select * from service_order_items where id=${p.data.itemId} and service_order_id=${p.data.id}`));if(!old)return reply.code(404).send({error:'not_found'});const q=b.data.quantity??Number(old.quantity),u=b.data.unitPrice??Number(old.unit_price),d=b.data.discountAmount??Number(old.discount_amount);if(d>q*u)return reply.code(400).send({error:'invalid_request'});const [row]=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`update service_order_items set type=coalesce(${b.data.type??null},type),description=coalesce(${b.data.description??null},description),quantity=${q},unit_price=${u},discount_amount=${d},notes=case when ${'notes'in b.data} then ${b.data.notes??null} else notes end,updated_at=now() where id=${p.data.itemId} and service_order_id=${p.data.id} returning *`));await service.auditResource(s,'service_order_item.updated','service_order',p.data.id);return row;});
 app.delete('/service-orders/:id/items/:itemId',async(req,reply)=>{const p=z.object({id,itemId:id}).safeParse(req.params);if(!p.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'service_orders.update'))return;const [row]=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`delete from service_order_items where id=${p.data.itemId} and service_order_id=${p.data.id} returning id`));if(!row)return reply.code(404).send({error:'not_found'});await service.auditResource(s,'service_order_item.deleted','service_order',p.data.id);return {deleted:true};});
}
