import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import { sql } from 'drizzle-orm';
import { z } from 'zod';
import type { AuthService, AuthSession, ResourceScope } from '../auth/service.js';
import { requirePermission } from '../auth/service.js';

const digits = (value: string) => value.replace(/\D/g, '');
const optionalText = (max: number) => z.string().trim().max(max).nullable().optional();
const phone = z.string().trim().max(30).transform(digits).refine((value) => value.length >= 8 && value.length <= 15).nullable().optional();
const address = z.object({ postalCode: z.string().trim().max(10).transform(digits).refine((v) => v.length === 8).nullable().optional(), street: z.string().trim().min(1).max(200), number: optionalText(30), complement: optionalText(100), district: optionalText(100), city: z.string().trim().min(1).max(100), state: z.string().trim().toUpperCase().regex(/^[A-Z]{2}$/).nullable().optional(), country: z.string().trim().toUpperCase().regex(/^[A-Z]{2}$/).default('BR') }).strict();
const base = z.object({
  personType: z.enum(['individual','company']), legalName: z.string().trim().min(1).max(200), tradeName: optionalText(200), document: z.string().trim().max(24).nullable().optional(),
  rgStateRegistration: optionalText(32), phone, mobile: phone, whatsapp: phone, email: z.string().trim().toLowerCase().email().max(254).nullable().optional(), notes: optionalText(4000),
  status: z.enum(['active','inactive']).default('active'), originCompanyId: z.string().uuid().nullable().optional(), originBranchId: z.string().uuid().nullable().optional(), address: address.nullable().optional(),
}).strict();
const update = base.omit({ originCompanyId: true, originBranchId: true }).partial().strict();
const paramsSchema = z.object({ id: z.string().uuid() });
const listSchema = z.object({ search: z.string().trim().max(100).optional(), page: z.coerce.number().int().min(1).default(1), pageSize: z.coerce.number().int().min(1).max(100).default(20) }).strict();
const contactSchema = z.object({ contactType: z.enum(['phone','mobile','whatsapp','email']), label: optionalText(80), value: z.string().trim().min(1).max(254), isPrimary: z.boolean().default(false) }).strict();
const addressSchema = address.extend({ addressType: z.enum(['main','billing','shipping','other']).default('main'), isPrimary: z.boolean().default(true) }).strict();

function validCpf(value: string) { if (!/^\d{11}$/.test(value) || /^(\d)\1+$/.test(value)) return false; for (const size of [9,10]) { let sum=0; for(let i=0;i<size;i++)sum+=Number(value[i])*(size+1-i); const digit=((sum*10)%11)%10; if(digit!==Number(value[size]))return false; } return true; }
function validCnpj(value: string) { if (!/^\d{14}$/.test(value) || /^(\d)\1+$/.test(value)) return false; for(const size of [12,13]) { const weights=size===12?[5,4,3,2,9,8,7,6,5,4,3,2]:[6,5,4,3,2,9,8,7,6,5,4,3,2]; const sum=weights.reduce((acc,w,i)=>acc+Number(value[i])*w,0); const rest=sum%11; if(Number(value[size])!==(rest<2?0:11-rest))return false; } return true; }
function normalizedDocument(personType: 'individual'|'company', document?: string|null) { if (!document) return null; const value=digits(document); const valid=personType==='individual'?validCpf(value):validCnpj(value); if(!valid) throw new Error('INVALID_DOCUMENT'); return value; }
const scopeFor = (session: AuthSession): ResourceScope => session.activeBranchId ? { companyId: session.activeCompanyId!, branchId: session.activeBranchId } : session.activeCompanyId ? { companyId: session.activeCompanyId } : { requireTenant: true };
const serializeCustomer = <T extends Record<string, unknown>>(row: T) => ({ ...row, ...(row.customer_number !== undefined ? { customer_number: Number(row.customer_number) } : {}) });
const isDuplicate = (error: unknown) => { if (typeof error !== 'object' || !error) return false; const candidate=error as { code?: string; cause?: { code?: string } }; return candidate.code==='23505' || candidate.cause?.code==='23505'; };

export function registerCustomerRoutes(app: FastifyInstance, service: AuthService) {
  async function authenticated(request: FastifyRequest, reply: FastifyReply) { const session=await service.session(request.cookies.vetoros_session); if(!session){reply.code(401).send({error:'unauthorized'});return;} if(!session.activeTenantId){reply.code(409).send({error:'tenant_required'});return;} return session; }
  async function authorize(reply: FastifyReply, session: AuthSession, permission: string) { try { await requirePermission(service,session,permission,scopeFor(session));return true; } catch { reply.code(403).send({error:'forbidden'});return false; } }
  async function validateOrigin(session: AuthSession, companyId?: string|null, branchId?: string|null) {
    const originCompanyId=companyId??session.activeCompanyId; const originBranchId=branchId??(originCompanyId===session.activeCompanyId?session.activeBranchId:null);
    if(!originCompanyId && originBranchId)return null;
    if(!originCompanyId)return {originCompanyId:null,originBranchId:null};
    if(!await service.hasPermission(session,'customers.create',{companyId:originCompanyId,...(originBranchId?{branchId:originBranchId}:{})}))return null;
    const rows=await service.withAuthenticatedTenant(session,tx=>tx.execute(sql`select c.id from companies c left join branches b on b.tenant_id=c.tenant_id and b.company_id=c.id and b.id=${originBranchId} where c.id=${originCompanyId} and c.status='active' and (${originBranchId}::uuid is null or b.id is not null) limit 1`));
    return rows.length?{originCompanyId,originBranchId}:null;
  }
  app.get('/customers',async(request,reply)=>{const query=listSchema.safeParse(request.query);if(!query.success)return reply.code(400).send({error:'invalid_request'});const session=await authenticated(request,reply);if(!session||!await authorize(reply,session,'customers.read'))return;
    const {search,page,pageSize}=query.data, offset=(page-1)*pageSize, normalized=search?digits(search):''; const prefix=search?`${search.toLocaleLowerCase('pt-BR')}%`:null, digitPrefix=normalized?`${normalized}%`:null;
    const rows=await service.withAuthenticatedTenant(session,tx=>tx.execute(sql`select c.*,a.id as address_id,a.postal_code,a.street,a.number,a.complement,a.district,a.city,a.state,a.country,count(*) over()::int as total from customers c left join customer_addresses a on a.customer_id=c.id and a.is_primary where (${prefix}::text is null or lower(c.legal_name) like ${prefix} or lower(c.trade_name) like ${prefix} or c.document_normalized like ${digitPrefix} or c.phone like ${digitPrefix} or c.mobile like ${digitPrefix} or lower(c.email) like ${prefix} or c.customer_number::text like ${digitPrefix}) order by c.customer_number desc limit ${pageSize} offset ${offset}`));
    return {items:rows.map(row=>serializeCustomer(Object.fromEntries(Object.entries(row).filter(([key])=>key!=='total')))),page,pageSize,total:Number(rows[0]?.total??0)};
  });
  app.get('/customers/:id',async(request,reply)=>{const params=paramsSchema.safeParse(request.params);if(!params.success)return reply.code(400).send({error:'invalid_request'});const session=await authenticated(request,reply);if(!session||!await authorize(reply,session,'customers.read'))return;const rows=await service.withAuthenticatedTenant(session,tx=>tx.execute(sql`select c.*,a.id as address_id,a.postal_code,a.street,a.number,a.complement,a.district,a.city,a.state,a.country from customers c left join customer_addresses a on a.customer_id=c.id and a.is_primary where c.id=${params.data.id}`));return rows[0]?serializeCustomer(rows[0]):reply.code(404).send({error:'not_found'});});
  app.post('/customers',async(request,reply)=>{const parsed=base.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'invalid_request',issues:parsed.error.issues.map(i=>i.path.join('.'))});const session=await authenticated(request,reply);if(!session||!await authorize(reply,session,'customers.create'))return;let document:string|null;try{document=normalizedDocument(parsed.data.personType,parsed.data.document);}catch{return reply.code(400).send({error:'invalid_document'});}const origin=await validateOrigin(session,parsed.data.originCompanyId,parsed.data.originBranchId);if(!origin)return reply.code(403).send({error:'origin_forbidden'});
    try { const raw=await service.withAuthenticatedTenant(session,async tx=>{const [counter]=await tx.execute<{last_number:number}>(sql`insert into customer_number_counters(tenant_id,last_number) values(${session.activeTenantId!},1) on conflict(tenant_id) do update set last_number=customer_number_counters.last_number+1,updated_at=now() returning last_number`);const number=Number(counter!.last_number);const [customer]=await tx.execute(sql`insert into customers(tenant_id,customer_number,person_type,legal_name,trade_name,document_type,document_normalized,rg_state_registration,phone,mobile,whatsapp,email,notes,status,origin_company_id,origin_branch_id,created_by_identity_id,updated_by_identity_id) values(${session.activeTenantId!},${number},${parsed.data.personType},${parsed.data.legalName},${parsed.data.tradeName??null},${document?(parsed.data.personType==='individual'?'cpf':'cnpj'):null},${document},${parsed.data.rgStateRegistration??null},${parsed.data.phone??null},${parsed.data.mobile??null},${parsed.data.whatsapp??null},${parsed.data.email??null},${parsed.data.notes??null},${parsed.data.status},${origin.originCompanyId},${origin.originBranchId},${session.identityId},${session.identityId}) returning *`);if(parsed.data.address)await tx.execute(sql`insert into customer_addresses(tenant_id,customer_id,postal_code,street,number,complement,district,city,state,country) values(${session.activeTenantId!},${customer!.id},${parsed.data.address.postalCode??null},${parsed.data.address.street},${parsed.data.address.number??null},${parsed.data.address.complement??null},${parsed.data.address.district??null},${parsed.data.address.city},${parsed.data.address.state??null},${parsed.data.address.country})`);return customer!;});const row=serializeCustomer(raw);await service.auditResource(session,'customer.created','customer',String(row.id),{customerNumber:row.customer_number,personType:parsed.data.personType,originCompanyId:origin.originCompanyId,originBranchId:origin.originBranchId});return reply.code(201).send(row); } catch(error){if(isDuplicate(error))return reply.code(409).send({error:'document_already_exists'});throw error;}
  });
  app.patch('/customers/:id',async(request,reply)=>{const params=paramsSchema.safeParse(request.params),parsed=update.safeParse(request.body);if(!params.success||!parsed.success||Object.keys(parsed.data).length===0)return reply.code(400).send({error:'invalid_request'});const session=await authenticated(request,reply);if(!session||!await authorize(reply,session,'customers.update'))return;const [current]=await service.withAuthenticatedTenant(session,tx=>tx.execute<{person_type:'individual'|'company';document_normalized:string|null;status:string}>(sql`select person_type,document_normalized,status from customers where id=${params.data.id}`));if(!current)return reply.code(404).send({error:'not_found'});const personType=parsed.data.personType??current.person_type;let document=current.document_normalized;try{if('document'in parsed.data)document=normalizedDocument(personType,parsed.data.document);else if(parsed.data.personType&&document)document=normalizedDocument(personType,document);}catch{return reply.code(400).send({error:'invalid_document'});}
    try{const raw=await service.withAuthenticatedTenant(session,async tx=>{const [customer]=await tx.execute(sql`update customers set person_type=${personType},legal_name=coalesce(${parsed.data.legalName??null},legal_name),trade_name=case when ${'tradeName'in parsed.data} then ${parsed.data.tradeName??null} else trade_name end,document_type=${document?(personType==='individual'?'cpf':'cnpj'):null},document_normalized=${document},rg_state_registration=case when ${'rgStateRegistration'in parsed.data} then ${parsed.data.rgStateRegistration??null} else rg_state_registration end,phone=case when ${'phone'in parsed.data} then ${parsed.data.phone??null} else phone end,mobile=case when ${'mobile'in parsed.data} then ${parsed.data.mobile??null} else mobile end,whatsapp=case when ${'whatsapp'in parsed.data} then ${parsed.data.whatsapp??null} else whatsapp end,email=case when ${'email'in parsed.data} then ${parsed.data.email??null} else email end,notes=case when ${'notes'in parsed.data} then ${parsed.data.notes??null} else notes end,status=coalesce(${parsed.data.status??null},status),updated_by_identity_id=${session.identityId},updated_at=now() where id=${params.data.id} returning *`);if(parsed.data.address){await tx.execute(sql`update customer_addresses set is_primary=false,updated_at=now() where customer_id=${params.data.id} and is_primary`);await tx.execute(sql`insert into customer_addresses(tenant_id,customer_id,postal_code,street,number,complement,district,city,state,country) values(${session.activeTenantId!},${params.data.id},${parsed.data.address.postalCode??null},${parsed.data.address.street},${parsed.data.address.number??null},${parsed.data.address.complement??null},${parsed.data.address.district??null},${parsed.data.address.city},${parsed.data.address.state??null},${parsed.data.address.country})`);}return customer!;});const row=serializeCustomer(raw);const statusChanged=parsed.data.status!==undefined&&parsed.data.status!==current.status;await service.auditResource(session,statusChanged?'customer.status_changed':'customer.updated','customer',params.data.id,{changedFields:Object.keys(parsed.data).filter(k=>!['document','notes'].includes(k))});return row;}catch(error){if(isDuplicate(error))return reply.code(409).send({error:'document_already_exists'});throw error;}
  });
  app.get('/customers/:id/contacts', async (request,reply)=>{const params=paramsSchema.safeParse(request.params);if(!params.success)return reply.code(400).send({error:'invalid_request'});const session=await authenticated(request,reply);if(!session||!await authorize(reply,session,'customers.read'))return;return service.withAuthenticatedTenant(session,tx=>tx.execute(sql`select * from customer_contacts where customer_id=${params.data.id} order by is_primary desc,created_at`));});
  app.post('/customers/:id/contacts', async (request,reply)=>{const params=paramsSchema.safeParse(request.params),body=contactSchema.safeParse(request.body);if(!params.success||!body.success)return reply.code(400).send({error:'invalid_request'});const session=await authenticated(request,reply);if(!session||!await authorize(reply,session,'customers.update'))return;const normalized=body.data.contactType==='email'?body.data.value.trim().toLowerCase():digits(body.data.value);if(body.data.contactType!=='email'&&(normalized.length<8||normalized.length>15))return reply.code(400).send({error:'invalid_contact'});try{const row=await service.withAuthenticatedTenant(session,async tx=>{const exists=await tx.execute(sql`select id from customers where id=${params.data.id}`);if(!exists.length)return null;if(body.data.isPrimary)await tx.execute(sql`update customer_contacts set is_primary=false,updated_at=now() where customer_id=${params.data.id} and contact_type=${body.data.contactType}`);const [created]=await tx.execute(sql`insert into customer_contacts(tenant_id,customer_id,contact_type,label,value,value_normalized,is_primary) values(${session.activeTenantId!},${params.data.id},${body.data.contactType},${body.data.label??null},${body.data.value},${normalized},${body.data.isPrimary}) returning *`);return created;});if(!row)return reply.code(404).send({error:'not_found'});await service.auditResource(session,'customer.contact.created','customer',params.data.id,{contactType:body.data.contactType});return reply.code(201).send(row);}catch(error){if(isDuplicate(error))return reply.code(409).send({error:'primary_contact_already_exists'});throw error;}});
  app.get('/customers/:id/addresses', async (request,reply)=>{const params=paramsSchema.safeParse(request.params);if(!params.success)return reply.code(400).send({error:'invalid_request'});const session=await authenticated(request,reply);if(!session||!await authorize(reply,session,'customers.read'))return;return service.withAuthenticatedTenant(session,tx=>tx.execute(sql`select * from customer_addresses where customer_id=${params.data.id} order by is_primary desc,created_at`));});
  app.post('/customers/:id/addresses', async (request,reply)=>{const params=paramsSchema.safeParse(request.params),body=addressSchema.safeParse(request.body);if(!params.success||!body.success)return reply.code(400).send({error:'invalid_request'});const session=await authenticated(request,reply);if(!session||!await authorize(reply,session,'customers.update'))return;const row=await service.withAuthenticatedTenant(session,async tx=>{const exists=await tx.execute(sql`select id from customers where id=${params.data.id}`);if(!exists.length)return null;if(body.data.isPrimary)await tx.execute(sql`update customer_addresses set is_primary=false,updated_at=now() where customer_id=${params.data.id}`);const [created]=await tx.execute(sql`insert into customer_addresses(tenant_id,customer_id,address_type,postal_code,street,number,complement,district,city,state,country,is_primary) values(${session.activeTenantId!},${params.data.id},${body.data.addressType},${body.data.postalCode??null},${body.data.street},${body.data.number??null},${body.data.complement??null},${body.data.district??null},${body.data.city},${body.data.state??null},${body.data.country},${body.data.isPrimary}) returning *`);return created;});if(!row)return reply.code(404).send({error:'not_found'});await service.auditResource(session,'customer.address.created','customer',params.data.id,{addressType:body.data.addressType});return reply.code(201).send(row);});
}
