// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import { sql } from 'drizzle-orm';
import { z } from 'zod';
import type { AuthService, AuthSession, ResourceScope } from '../auth/service.js';
import { requirePermission } from '../auth/service.js';

const id=z.string().uuid();
const statuses=['draft','sent','approved','rejected','expired','cancelled'] as const;
const params=z.object({id});
const createSchema=z.object({customerId:id,customerAssetId:id.nullable().optional(),title:z.string().trim().min(1).max(200),notes:z.string().trim().max(4000).nullable().optional(),validUntil:z.string().date().nullable().optional()}).strict();
const updateSchema=z.object({customerAssetId:id.nullable().optional(),title:z.string().trim().min(1).max(200).optional(),notes:z.string().trim().max(4000).nullable().optional(),validUntil:z.string().date().nullable().optional(),status:z.enum(statuses).optional()}).strict();
const listSchema=z.object({search:z.string().trim().max(100).optional(),customerId:id.optional(),status:z.enum(statuses).optional(),page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(20),order:z.enum(['newest','oldest','number_asc','number_desc']).default('newest')}).strict();
const itemCreate=z.object({type:z.enum(['service','part']),description:z.string().trim().min(1).max(300),quantity:z.coerce.number().positive(),unitPrice:z.coerce.number().nonnegative(),discountAmount:z.coerce.number().nonnegative().default(0),notes:z.string().trim().max(2000).nullable().optional()}).strict();
const itemUpdate=itemCreate.partial().strict();
const scope=(s:AuthSession):ResourceScope=>s.activeBranchId?{companyId:s.activeCompanyId!,branchId:s.activeBranchId}:s.activeCompanyId?{companyId:s.activeCompanyId}:{requireTenant:true};
const transitions:Record<string,string[]>={draft:['sent','cancelled'],sent:['approved','rejected','expired','cancelled'],approved:[],rejected:[],expired:[],cancelled:[]};

export function registerQuoteRoutes(app:FastifyInstance,service:AuthService){
 async function auth(req:FastifyRequest,reply:FastifyReply){const s=await service.session(req.cookies.vetoros_session);if(!s){reply.code(401).send({error:'unauthorized'});return;}if(!s.activeTenantId||!s.activeCompanyId||!s.activeBranchId){reply.code(409).send({error:'operational_context_required'});return;}return s;}
 async function allow(reply:FastifyReply,s:AuthSession,p:string){try{await requirePermission(service,s,p,scope(s));return true;}catch{reply.code(403).send({error:'forbidden'});return false;}}
 async function quote(s:AuthSession,quoteId:string){return service.withAuthenticatedTenant(s,async tx=>{const [row]=await tx.execute(sql`select q.*,c.legal_name customer_name,a.internal_identifier asset_identifier,b.name branch_name from quotes q join customers c on c.id=q.customer_id left join customer_assets a on a.id=q.customer_asset_id join branches b on b.id=q.branch_id where q.id=${quoteId}`);if(!row)return null;const items=await tx.execute(sql`select * from quote_items where quote_id=${quoteId} order by created_at`);return {...row,items,subtotal:items.reduce((n,i)=>n+Number(i.quantity)*Number(i.unit_price),0),discounts:items.reduce((n,i)=>n+Number(i.discount_amount),0),total:items.reduce((n,i)=>n+Number(i.total_amount),0)};});}

 app.get('/quotes',async(req,reply)=>{const q=listSchema.safeParse(req.query);if(!q.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'quotes.read'))return;const offset=(q.data.page-1)*q.data.pageSize,term=q.data.search?`%${q.data.search}%`:null;const ordering=q.data.order==='oldest'?sql`q.created_at asc`:q.data.order==='number_asc'?sql`q.quote_number asc`:q.data.order==='number_desc'?sql`q.quote_number desc`:sql`q.created_at desc`;const rows=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`select q.*,c.legal_name customer_name,count(*) over()::int total from quotes q join customers c on c.id=q.customer_id where (${q.data.customerId??null}::uuid is null or q.customer_id=${q.data.customerId??null}) and (${q.data.status??null}::text is null or q.status=${q.data.status??null}) and (${term}::text is null or q.quote_number::text ilike ${term} or q.title ilike ${term} or c.legal_name ilike ${term}) order by ${ordering} limit ${q.data.pageSize} offset ${offset}`));return{items:rows.map(r=>Object.fromEntries(Object.entries(r).filter(([k])=>k!=='total'))),page:q.data.page,pageSize:q.data.pageSize,total:Number(rows[0]?.total??0)};});
 app.get('/quotes/:id',async(req,reply)=>{const p=params.safeParse(req.params);if(!p.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'quotes.read'))return;return await quote(s,p.data.id)??reply.code(404).send({error:'not_found'});});
 app.post('/quotes',async(req,reply)=>{const b=createSchema.safeParse(req.body);if(!b.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'quotes.create'))return;const result=await service.withAuthenticatedTenant(s,async tx=>{const customers=await tx.execute(sql`select id from customers where id=${b.data.customerId}`);if(!customers.length)return 'customer';if(b.data.customerAssetId){const assets=await tx.execute(sql`select id from customer_assets where id=${b.data.customerAssetId} and customer_id=${b.data.customerId}`);if(!assets.length)return 'asset';}const [counter]=await tx.execute(sql`insert into quote_number_counters(tenant_id,last_number) values(${s.activeTenantId!},1) on conflict(tenant_id) do update set last_number=quote_number_counters.last_number+1,updated_at=now() returning last_number`);const [row]=await tx.execute(sql`insert into quotes(tenant_id,company_id,branch_id,quote_number,customer_id,customer_asset_id,title,notes,valid_until,created_by_identity_id,updated_by_identity_id) values(${s.activeTenantId!},${s.activeCompanyId!},${s.activeBranchId!},${counter!.last_number},${b.data.customerId},${b.data.customerAssetId??null},${b.data.title},${b.data.notes??null},${b.data.validUntil??null},${s.identityId},${s.identityId}) returning *`);return row;});if(result==='customer')return reply.code(404).send({error:'customer_not_found'});if(result==='asset')return reply.code(400).send({error:'asset_customer_mismatch'});await service.auditResource(s,'quote.created','quote',result.id);return reply.code(201).send(result);});
 app.patch('/quotes/:id',async(req,reply)=>{const p=params.safeParse(req.params),b=updateSchema.safeParse(req.body);if(!p.success||!b.success||!Object.keys(b.data).length)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'quotes.update'))return;const result=await service.withAuthenticatedTenant(s,async tx=>{const [old]=await tx.execute(sql`select * from quotes where id=${p.data.id} for update`);if(!old)return 'missing';if(old.converted_service_order_id)return 'converted';if(b.data.status&&b.data.status!==old.status&&!transitions[old.status].includes(b.data.status))return 'transition';if('customerAssetId'in b.data&&b.data.customerAssetId){const assets=await tx.execute(sql`select id from customer_assets where id=${b.data.customerAssetId} and customer_id=${old.customer_id}`);if(!assets.length)return 'asset';}const [row]=await tx.execute(sql`update quotes set customer_asset_id=case when ${'customerAssetId'in b.data} then ${b.data.customerAssetId??null} else customer_asset_id end,title=coalesce(${b.data.title??null},title),notes=case when ${'notes'in b.data} then ${b.data.notes??null} else notes end,valid_until=case when ${'validUntil'in b.data} then ${b.data.validUntil??null} else valid_until end,status=coalesce(${b.data.status??null},status),updated_by_identity_id=${s.identityId},updated_at=now() where id=${p.data.id} returning *`);return row;});if(result==='missing')return reply.code(404).send({error:'not_found'});if(result==='converted')return reply.code(409).send({error:'quote_already_converted'});if(result==='transition')return reply.code(409).send({error:'invalid_status_transition'});if(result==='asset')return reply.code(400).send({error:'asset_customer_mismatch'});await service.auditResource(s,b.data.status?'quote.status_changed':'quote.updated','quote',p.data.id,{status:b.data.status});return result;});
 app.get('/quotes/:id/items',async(req,reply)=>{const p=params.safeParse(req.params);if(!p.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'quotes.read'))return;const found=await quote(s,p.data.id);return found?found.items:reply.code(404).send({error:'not_found'});});
 app.post('/quotes/:id/items',async(req,reply)=>{const p=params.safeParse(req.params),b=itemCreate.safeParse(req.body);if(!p.success||!b.success||b.data.discountAmount>b.data.quantity*b.data.unitPrice)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'quotes.update'))return;const result=await service.withAuthenticatedTenant(s,async tx=>{const [q]=await tx.execute(sql`select status,converted_service_order_id from quotes where id=${p.data.id}`);if(!q)return null;if(q.status!=='draft'||q.converted_service_order_id)return 'locked';const [row]=await tx.execute(sql`insert into quote_items(tenant_id,quote_id,type,description,quantity,unit_price,discount_amount,notes) values(${s.activeTenantId!},${p.data.id},${b.data.type},${b.data.description},${b.data.quantity},${b.data.unitPrice},${b.data.discountAmount},${b.data.notes??null}) returning *`);return row;});if(!result)return reply.code(404).send({error:'not_found'});if(result==='locked')return reply.code(409).send({error:'quote_not_editable'});await service.auditResource(s,'quote_item.created','quote',p.data.id);return reply.code(201).send(result);});
 app.patch('/quotes/:id/items/:itemId',async(req,reply)=>{const p=z.object({id,itemId:id}).safeParse(req.params),b=itemUpdate.safeParse(req.body);if(!p.success||!b.success||!Object.keys(b.data).length)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'quotes.update'))return;const result=await service.withAuthenticatedTenant(s,async tx=>{const [old]=await tx.execute(sql`select i.*,q.status,q.converted_service_order_id from quote_items i join quotes q on q.id=i.quote_id where i.id=${p.data.itemId} and i.quote_id=${p.data.id}`);if(!old)return null;if(old.status!=='draft'||old.converted_service_order_id)return 'locked';const quantity=b.data.quantity??Number(old.quantity),unitPrice=b.data.unitPrice??Number(old.unit_price),discount=b.data.discountAmount??Number(old.discount_amount);if(discount>quantity*unitPrice)return 'invalid';const [row]=await tx.execute(sql`update quote_items set type=coalesce(${b.data.type??null},type),description=coalesce(${b.data.description??null},description),quantity=${quantity},unit_price=${unitPrice},discount_amount=${discount},notes=case when ${'notes'in b.data} then ${b.data.notes??null} else notes end,updated_at=now() where id=${p.data.itemId} and quote_id=${p.data.id} returning *`);return row;});if(!result)return reply.code(404).send({error:'not_found'});if(result==='locked')return reply.code(409).send({error:'quote_not_editable'});if(result==='invalid')return reply.code(400).send({error:'invalid_request'});await service.auditResource(s,'quote_item.updated','quote',p.data.id);return result;});
 app.delete('/quotes/:id/items/:itemId',async(req,reply)=>{const p=z.object({id,itemId:id}).safeParse(req.params);if(!p.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'quotes.update'))return;const result=await service.withAuthenticatedTenant(s,async tx=>{const [q]=await tx.execute(sql`select status,converted_service_order_id from quotes where id=${p.data.id}`);if(!q)return 'missing';if(q.status!=='draft'||q.converted_service_order_id)return 'locked';const [row]=await tx.execute(sql`delete from quote_items where id=${p.data.itemId} and quote_id=${p.data.id} returning id`);return row??null;});if(result==='missing'||!result)return reply.code(404).send({error:'not_found'});if(result==='locked')return reply.code(409).send({error:'quote_not_editable'});await service.auditResource(s,'quote_item.deleted','quote',p.data.id);return{deleted:true};});
 app.post('/quotes/:id/convert',async(req,reply)=>{const p=params.safeParse(req.params);if(!p.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'quotes.update')||!await allow(reply,s,'service_orders.create'))return;const result=await service.withAuthenticatedTenant(s,async tx=>{const [q]=await tx.execute(sql`select * from quotes where id=${p.data.id} for update`);if(!q)return 'missing';if(q.converted_service_order_id)return {id:q.converted_service_order_id,idempotent:true};if(q.status!=='approved')return 'status';const [counter]=await tx.execute(sql`insert into service_order_number_counters(tenant_id,last_number) values(${s.activeTenantId!},1) on conflict(tenant_id) do update set last_number=service_order_number_counters.last_number+1,updated_at=now() returning last_number`);const [order]=await tx.execute(sql`insert into service_orders(tenant_id,company_id,branch_id,order_number,customer_id,asset_id,title,reported_problem,initial_notes,created_by_identity_id,updated_by_identity_id) values(${q.tenant_id},${q.company_id},${q.branch_id},${counter!.last_number},${q.customer_id},${q.customer_asset_id},${q.title},${q.title},${q.notes},${s.identityId},${s.identityId}) returning *`);await tx.execute(sql`insert into service_order_items(tenant_id,service_order_id,type,description,quantity,unit_price,discount_amount,notes) select tenant_id,${order!.id},type,description,quantity,unit_price,discount_amount,notes from quote_items where quote_id=${q.id}`);await tx.execute(sql`update quotes set converted_service_order_id=${order!.id},updated_at=now(),updated_by_identity_id=${s.identityId} where id=${q.id}`);return order;});if(result==='missing')return reply.code(404).send({error:'not_found'});if(result==='status')return reply.code(409).send({error:'quote_not_approved'});await service.auditResource(s,'quote.converted','quote',p.data.id,{serviceOrderId:result.id});return reply.code(result.idempotent?200:201).send(result);});
}
