'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { api } from '../../lib/api';
import Link from 'next/link';

export default function AuthenticatedPage() {
  const router = useRouter(); const [data, setData] = useState<{activeTenantId:string;activeCompanyId:string|null;activeBranchId:string|null;profile:{companies:Array<{id:string;legal_name:string}>;branches:Array<{id:string;company_id:string;name:string}>}}>();
  useEffect(() => { void api('/auth/session').then(async (response) => { if (!response.ok) return router.replace('/login'); const value = await response.json(); if (!value.activeTenantId) return router.replace('/select-tenant'); setData(value); }); }, [router]);
  async function select(companyId: string, branchId?: string) { const response=await api('/auth/operational-context',{method:'POST',body:JSON.stringify({companyId,...(branchId?{branchId}:{})})});if(response.status===401)return router.replace('/login');if(!response.ok)return;router.refresh();setData((current)=>current?{...current,activeCompanyId:companyId,activeBranchId:branchId??null}:current); }
  async function logout() { await api('/auth/logout', { method: 'POST' }); router.replace('/login'); router.refresh(); }
  return <main className="grid min-h-screen place-items-center p-6"><section className="w-full max-w-2xl rounded-3xl border border-emerald-800 bg-emerald-950/40 p-10"><p className="text-emerald-400">Sessão autenticada</p><h1 className="mt-2 text-4xl font-bold">VetorOS 2</h1><p className="mt-5 text-sm text-emerald-100/70">Tenant: {data?.activeTenantId ?? 'validando…'}</p>
    {data&&<div className="mt-6 grid gap-3 sm:grid-cols-2"><select aria-label="Empresa ativa" value={data.activeCompanyId??''} onChange={(e)=>select(e.target.value)} className="rounded-xl bg-emerald-950 p-3"><option value="">Selecione a empresa</option>{data.profile.companies.map(c=><option key={c.id} value={c.id}>{c.legal_name}</option>)}</select><select aria-label="Filial ativa" value={data.activeBranchId??''} disabled={!data.activeCompanyId} onChange={(e)=>select(data.activeCompanyId!,e.target.value)} className="rounded-xl bg-emerald-950 p-3"><option value="">Selecione a filial</option>{data.profile.branches.filter(b=>b.company_id===data.activeCompanyId).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></div>}
    <nav className="mt-8 flex gap-4"><Link href="/app/companies" className="text-emerald-300 underline">Empresas</Link><Link href="/app/branches" className="text-emerald-300 underline">Filiais</Link><Link href="/app/customers" className="text-emerald-300 underline">Clientes</Link><Link href="/app/assets" className="text-emerald-300 underline">Equipamentos</Link><Link href="/app/suppliers" className="text-emerald-300 underline">Fornecedores</Link><Link href="/app/purchase-orders" className="text-emerald-300 underline">Pedidos de compra</Link><Link href="/app/purchase-receipts" className="text-emerald-300 underline">Recebimentos</Link><Link href="/app/quotes" className="text-emerald-300 underline">Orçamentos</Link><Link href="/app/service-orders" className="text-emerald-300 underline">Ordens de serviço</Link><Link href="/app/inventory" className="text-emerald-300 underline">Estoque</Link></nav><button onClick={logout} className="mt-8 rounded-xl border border-emerald-600 px-5 py-3">Sair</button></section></main>;
}
