// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
/* eslint-disable @typescript-eslint/no-explicit-any */
import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import { sql } from 'drizzle-orm';
import { z } from 'zod';
import type { AuthService, AuthSession, ResourceScope } from '../auth/service.js';
import { requirePermission } from '../auth/service.js';

const id=z.string().uuid(), params=z.object({id});
const instant=z.string().datetime({offset:true});
const createSchema=z.object({serviceOrderId:id.nullable().optional(),customerId:id.optional(),assetId:id.nullable().optional(),responsibleUserProfileId:id.nullable().optional(),startsAt:instant,endsAt:instant.nullable().optional(),notes:z.string().trim().max(4000).nullable().optional()}).strict();
const updateSchema=z.object({responsibleUserProfileId:id.nullable().optional(),startsAt:instant.optional(),endsAt:instant.nullable().optional(),notes:z.string().trim().max(4000).nullable().optional()}).strict();
const listSchema=z.object({from:instant.optional(),to:instant.optional(),responsibleUserProfileId:id.optional(),serviceOrderId:id.optional(),status:z.enum(['scheduled','canceled']).optional(),page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(30)}).strict();
const scope=(s:AuthSession):ResourceScope=>({companyId:s.activeCompanyId!,branchId:s.activeBranchId!});

export function registerScheduleRoutes(app:FastifyInstance,service:AuthService){
 async function auth(req:FastifyRequest,reply:FastifyReply){const s=await service.session(req.cookies.vetoros_session);if(!s){reply.code(401).send({error:'unauthorized'});return;}if(!s.activeTenantId||!s.activeCompanyId||!s.activeBranchId){reply.code(409).send({error:'operational_context_required'});return;}return s;}
 async function allow(reply:FastifyReply,s:AuthSession,p:string){try{await requirePermission(service,s,p,scope(s));return true;}catch{reply.code(403).send({error:'forbidden'});return false;}}
 async function conflicts(tx:any,s:AuthSession,responsible:string|null,start:string,end:string|null,exclude:string|null){if(!responsible)return[];return tx.execute(sql`select sc.id,sc.starts_at,sc.ends_at,c.legal_name customer_name,o.order_number service_order_number from schedules sc join customers c on c.id=sc.customer_id left join service_orders o on o.id=sc.service_order_id where sc.branch_id=${s.activeBranchId!} and sc.responsible_user_profile_id=${responsible} and sc.status='scheduled' and (${exclude}::uuid is null or sc.id<>${exclude}) and ((sc.ends_at is null and sc.starts_at=${start}::timestamptz) or (${end}::timestamptz is null and sc.starts_at=${start}::timestamptz) or (sc.ends_at is not null and ${end}::timestamptz is not null and sc.starts_at<${end}::timestamptz and sc.ends_at>${start}::timestamptz)) order by sc.starts_at`);}
 function dbError(reply:FastifyReply,e:any){const code=e?.code??e?.cause?.code,message=e?.message??e?.cause?.message??'';if(code==='23514'){const error=message.includes('responsible')?'responsible_not_authorized':message.includes('asset')?'asset_customer_mismatch':message.includes('scope')?'service_order_scope_mismatch':'invalid_schedule_relation';reply.code(400).send({error});return true;}return false;}

 app.get('/schedules',async(req,reply)=>{const q=listSchema.safeParse(req.query);if(!q.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'schedules.read'))return;const offset=(q.data.page-1)*q.data.pageSize;const rows=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`select sc.*,c.legal_name customer_name,a.internal_identifier asset_identifier,o.order_number service_order_number,p.name responsible_name,count(*) over()::int total from schedules sc join customers c on c.id=sc.customer_id left join customer_assets a on a.id=sc.asset_id left join service_orders o on o.id=sc.service_order_id left join tenant_user_profiles p on p.id=sc.responsible_user_profile_id where sc.branch_id=${s.activeBranchId!} and (${q.data.from??null}::timestamptz is null or sc.starts_at>=${q.data.from??null}) and (${q.data.to??null}::timestamptz is null or sc.starts_at<${q.data.to??null}) and (${q.data.responsibleUserProfileId??null}::uuid is null or sc.responsible_user_profile_id=${q.data.responsibleUserProfileId??null}) and (${q.data.serviceOrderId??null}::uuid is null or sc.service_order_id=${q.data.serviceOrderId??null}) and (${q.data.status??null}::text is null or sc.status=${q.data.status??null}) order by sc.starts_at,sc.id limit ${q.data.pageSize} offset ${offset}`));return{items:rows.map((r:any)=>Object.fromEntries(Object.entries(r).filter(([k])=>k!=='total'))),page:q.data.page,pageSize:q.data.pageSize,total:Number(rows[0]?.total??0)};});
 app.get('/schedules/assignees',async(req,reply)=>{const s=await auth(req,reply);if(!s||!await allow(reply,s,'schedules.read'))return;return service.withAuthenticatedTenant(s,tx=>tx.execute(sql`select distinct p.id,p.name from tenant_user_profiles p join tenant_memberships m on m.tenant_id=p.tenant_id and m.id=p.membership_id join access_grants g on g.tenant_id=p.tenant_id and g.user_profile_id=p.id join tenant_roles r on r.tenant_id=g.tenant_id and r.id=g.role_id where p.status='active' and m.status='active' and g.status='active' and r.status='active' and g.valid_from<=now() and (g.valid_until is null or g.valid_until>now()) and (g.scope_type='tenant' or (g.scope_type='company' and g.company_id=${s.activeCompanyId!}) or (g.scope_type='branch' and g.company_id=${s.activeCompanyId!} and g.branch_id=${s.activeBranchId!})) order by p.name`));});
 app.get('/schedules/:id',async(req,reply)=>{const p=params.safeParse(req.params);if(!p.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'schedules.read'))return;const [row]=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`select sc.*,c.legal_name customer_name,a.internal_identifier asset_identifier,o.order_number service_order_number,p.name responsible_name from schedules sc join customers c on c.id=sc.customer_id left join customer_assets a on a.id=sc.asset_id left join service_orders o on o.id=sc.service_order_id left join tenant_user_profiles p on p.id=sc.responsible_user_profile_id where sc.id=${p.data.id} and sc.branch_id=${s.activeBranchId!}`));return row??reply.code(404).send({error:'not_found'});});
 app.post('/schedules',async(req,reply)=>{const b=createSchema.safeParse(req.body);if(!b.success||(!b.data.serviceOrderId&&!b.data.customerId)||Boolean(b.data.endsAt&&new Date(b.data.endsAt)<=new Date(b.data.startsAt)))return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'schedules.create'))return;try{const result=await service.withAuthenticatedTenant(s,async tx=>{let customer=b.data.customerId??null,asset=b.data.assetId??null;if(b.data.serviceOrderId){const[o]=await tx.execute(sql`select customer_id,asset_id from service_orders where id=${b.data.serviceOrderId} and branch_id=${s.activeBranchId!}`);if(!o)return'missing_order';if(customer&&customer!==o.customer_id)return'customer_mismatch';if(o.asset_id&&asset&&asset!==o.asset_id)return'asset_mismatch';customer=o.customer_id;asset=o.asset_id??asset;}const[c]=await tx.execute(sql`select id from customers where id=${customer}`);if(!c)return'missing_customer';const [row]=await tx.execute(sql`insert into schedules(tenant_id,company_id,branch_id,service_order_id,customer_id,asset_id,responsible_user_profile_id,starts_at,ends_at,notes,created_by_identity_id,updated_by_identity_id) values(${s.activeTenantId!},${s.activeCompanyId!},${s.activeBranchId!},${b.data.serviceOrderId??null},${customer},${asset},${b.data.responsibleUserProfileId??null},${b.data.startsAt},${b.data.endsAt??null},${b.data.notes??null},${s.identityId},${s.identityId}) returning *`);return{row,warnings:await conflicts(tx,s,b.data.responsibleUserProfileId??null,b.data.startsAt,b.data.endsAt??null,row.id)};});if(result==='missing_order')return reply.code(404).send({error:'service_order_not_found'});if(result==='missing_customer')return reply.code(404).send({error:'customer_not_found'});if(result==='customer_mismatch')return reply.code(400).send({error:'service_order_customer_mismatch'});if(result==='asset_mismatch')return reply.code(400).send({error:'service_order_asset_mismatch'});await service.auditResource(s,'schedule.created','schedule',result.row.id,{warnings:result.warnings.length});return reply.code(201).send({...result.row,conflicts:result.warnings});}catch(e){if(dbError(reply,e))return;throw e;}});
 app.patch('/schedules/:id',async(req,reply)=>{const p=params.safeParse(req.params),b=updateSchema.safeParse(req.body);if(!p.success||!b.success||!Object.keys(b.data).length)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'schedules.update'))return;try{const result=await service.withAuthenticatedTenant(s,async tx=>{const[old]=await tx.execute(sql`select * from schedules where id=${p.data.id} and branch_id=${s.activeBranchId!} for update`);if(!old)return'missing';if(old.status!=='scheduled')return'canceled';const start=b.data.startsAt??old.starts_at,end='endsAt'in b.data?b.data.endsAt:old.ends_at;if(end&&new Date(end)<=new Date(start))return'invalid_time';const[row]=await tx.execute(sql`update schedules set responsible_user_profile_id=case when ${'responsibleUserProfileId'in b.data} then ${b.data.responsibleUserProfileId??null} else responsible_user_profile_id end,starts_at=${start},ends_at=${end??null},notes=case when ${'notes'in b.data} then ${b.data.notes??null} else notes end,updated_by_identity_id=${s.identityId},updated_at=now() where id=${p.data.id} returning *`);return{row,old,warnings:await conflicts(tx,s,row.responsible_user_profile_id,row.starts_at,row.ends_at,row.id)};});if(result==='missing')return reply.code(404).send({error:'not_found'});if(result==='canceled')return reply.code(409).send({error:'schedule_canceled'});if(result==='invalid_time')return reply.code(400).send({error:'invalid_time_range'});await service.auditResource(s,'schedule.updated','schedule',p.data.id,{rescheduled:String(result.old.starts_at)!==String(result.row.starts_at)||String(result.old.ends_at)!==String(result.row.ends_at),responsibleChanged:result.old.responsible_user_profile_id!==result.row.responsible_user_profile_id});return{...result.row,conflicts:result.warnings};}catch(e){if(dbError(reply,e))return;throw e;}});
 app.post('/schedules/:id/cancel',async(req,reply)=>{const p=params.safeParse(req.params);if(!p.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'schedules.cancel'))return;const result=await service.withAuthenticatedTenant(s,async tx=>{const[old]=await tx.execute(sql`select * from schedules where id=${p.data.id} and branch_id=${s.activeBranchId!} for update`);if(!old)return'missing';if(old.status==='canceled')return{row:old,idempotent:true};const[row]=await tx.execute(sql`update schedules set status='canceled',canceled_at=now(),canceled_by_identity_id=${s.identityId},updated_by_identity_id=${s.identityId},updated_at=now() where id=${p.data.id} returning *`);return{row,idempotent:false};});if(result==='missing')return reply.code(404).send({error:'not_found'});if(!result.idempotent)await service.auditResource(s,'schedule.canceled','schedule',p.data.id);return{...result.row,idempotent:result.idempotent};});
}
