// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import { sql } from 'drizzle-orm';
import { z } from 'zod';
import type { AuthService, AuthSession, ResourceScope } from '../auth/service.js';
import { requirePermission } from '../auth/service.js';
import { purchaseOrderReceiptState } from '../purchase-receipts/routes.js';

const id = z.string().uuid();
const statuses = ['draft', 'approved', 'cancelled'] as const;
const params = z.object({ id });
const createSchema = z.object({ supplierId: id, issueDate: z.string().date().optional(), expectedDate: z.string().date().nullable().optional(), supplierReference: z.string().trim().max(120).nullable().optional(), notes: z.string().trim().max(4000).nullable().optional(), freightTotal: z.coerce.number().nonnegative().optional(), otherCostsTotal: z.coerce.number().nonnegative().optional() }).strict();
const updateSchema = z.object({ expectedDate: z.string().date().nullable().optional(), supplierReference: z.string().trim().max(120).nullable().optional(), notes: z.string().trim().max(4000).nullable().optional(), freightTotal: z.coerce.number().nonnegative().optional(), otherCostsTotal: z.coerce.number().nonnegative().optional() }).strict();
const listSchema = z.object({ search: z.string().trim().max(100).optional(), supplierId: id.optional(), status: z.enum(statuses).optional(), branchId: id.optional(), issuedFrom: z.string().date().optional(), issuedTo: z.string().date().optional(), page: z.coerce.number().int().min(1).default(1), pageSize: z.coerce.number().int().min(1).max(100).default(20), order: z.enum(['newest', 'oldest', 'number_asc', 'number_desc']).default('newest') }).strict();
const itemCreate = z.object({ inventoryPartId: id, description: z.string().trim().min(1).max(300).optional(), quantity: z.coerce.number().positive(), unitCost: z.coerce.number().nonnegative(), discount: z.coerce.number().nonnegative().default(0), notes: z.string().trim().max(2000).nullable().optional() }).strict();
const itemUpdate = z.object({ description: z.string().trim().min(1).max(300).optional(), quantity: z.coerce.number().positive().optional(), unitCost: z.coerce.number().nonnegative().optional(), discount: z.coerce.number().nonnegative().optional(), notes: z.string().trim().max(2000).nullable().optional() }).strict();
const scope = (s: AuthSession): ResourceScope => s.activeBranchId ? { companyId: s.activeCompanyId!, branchId: s.activeBranchId } : s.activeCompanyId ? { companyId: s.activeCompanyId } : { requireTenant: true };
const transitions: Record<string, string[]> = { draft: ['approved', 'cancelled'], approved: [], cancelled: [] };

export function registerPurchaseOrderRoutes(app: FastifyInstance, service: AuthService) {
 async function auth(req: FastifyRequest, reply: FastifyReply) { const s = await service.session(req.cookies.vetoros_session); if (!s) { reply.code(401).send({ error: 'unauthorized' }); return; } if (!s.activeTenantId || !s.activeCompanyId || !s.activeBranchId) { reply.code(409).send({ error: 'operational_context_required' }); return; } return s; }
 async function allow(reply: FastifyReply, s: AuthSession, p: string) { try { await requirePermission(service, s, p, scope(s)); return true; } catch { reply.code(403).send({ error: 'forbidden' }); return false; } }
 async function order(s: AuthSession, orderId: string) { return service.withAuthenticatedTenant(s, async (tx) => { const [row] = await tx.execute(sql`select p.*,sup.legal_name supplier_name,b.name branch_name from purchase_orders p join suppliers sup on sup.id=p.supplier_id join branches b on b.id=p.branch_id where p.id=${orderId}`); if (!row) return null; const items = await tx.execute(sql`select i.*,ip.sku part_sku,coalesce((select sum(pri.quantity) from purchase_receipt_items pri join purchase_receipts pr on pr.id=pri.purchase_receipt_id where pri.purchase_order_item_id=i.id and pr.status='confirmed'),0) received_quantity from purchase_order_items i join inventory_parts ip on ip.id=i.inventory_part_id where i.purchase_order_id=${orderId} order by i.created_at`); const withPending = items.map((i) => ({ ...i, pending_quantity: Number(i.quantity) - Number(i.received_quantity) })); const receiptState = await purchaseOrderReceiptState(tx, orderId); return { ...row, items: withPending, receipt_state: receiptState }; }); }

 app.get('/purchase-orders', async (req, reply) => { const q = listSchema.safeParse(req.query); if (!q.success) return reply.code(400).send({ error: 'invalid_request' }); const s = await auth(req, reply); if (!s || !await allow(reply, s, 'purchase_orders.read')) return; const offset = (q.data.page - 1) * q.data.pageSize, term = q.data.search ? `%${q.data.search}%` : null; const ordering = q.data.order === 'oldest' ? sql`p.created_at asc` : q.data.order === 'number_asc' ? sql`p.purchase_order_number asc` : q.data.order === 'number_desc' ? sql`p.purchase_order_number desc` : sql`p.created_at desc`; const rows = await service.withAuthenticatedTenant(s, (tx) => tx.execute(sql`select p.*,sup.legal_name supplier_name,b.name branch_name,count(*) over()::int total from purchase_orders p join suppliers sup on sup.id=p.supplier_id join branches b on b.id=p.branch_id where (${q.data.supplierId ?? null}::uuid is null or p.supplier_id=${q.data.supplierId ?? null}) and (${q.data.status ?? null}::text is null or p.status=${q.data.status ?? null}) and (${q.data.branchId ?? null}::uuid is null or p.branch_id=${q.data.branchId ?? null}) and (${q.data.issuedFrom ?? null}::date is null or p.issue_date>=${q.data.issuedFrom ?? null}) and (${q.data.issuedTo ?? null}::date is null or p.issue_date<=${q.data.issuedTo ?? null}) and (${term}::text is null or p.purchase_order_number::text ilike ${term} or sup.legal_name ilike ${term} or p.supplier_reference ilike ${term}) order by ${ordering} limit ${q.data.pageSize} offset ${offset}`)); return { items: rows.map((r) => Object.fromEntries(Object.entries(r).filter(([k]) => k !== 'total'))), page: q.data.page, pageSize: q.data.pageSize, total: Number(rows[0]?.total ?? 0) }; });
 app.get('/purchase-orders/:id', async (req, reply) => { const p = params.safeParse(req.params); if (!p.success) return reply.code(400).send({ error: 'invalid_request' }); const s = await auth(req, reply); if (!s || !await allow(reply, s, 'purchase_orders.read')) return; return await order(s, p.data.id) ?? reply.code(404).send({ error: 'not_found' }); });
 app.post('/purchase-orders', async (req, reply) => { const b = createSchema.safeParse(req.body); if (!b.success) return reply.code(400).send({ error: 'invalid_request' }); const s = await auth(req, reply); if (!s || !await allow(reply, s, 'purchase_orders.create')) return; const issueDate = b.data.issueDate ?? new Date().toISOString().slice(0, 10); const result = await service.withAuthenticatedTenant(s, async (tx) => { const supplier = await tx.execute(sql`select id from suppliers where id=${b.data.supplierId}`); if (!supplier.length) return 'supplier'; const [counter] = await tx.execute(sql`insert into purchase_order_number_counters(tenant_id,last_number) values(${s.activeTenantId!},1) on conflict(tenant_id) do update set last_number=purchase_order_number_counters.last_number+1,updated_at=now() returning last_number`); const [row] = await tx.execute(sql`insert into purchase_orders(tenant_id,company_id,branch_id,purchase_order_number,supplier_id,issue_date,expected_date,supplier_reference,notes,freight_total,other_costs_total,created_by_identity_id,updated_by_identity_id) values(${s.activeTenantId!},${s.activeCompanyId!},${s.activeBranchId!},${counter!.last_number},${b.data.supplierId},${issueDate},${b.data.expectedDate ?? null},${b.data.supplierReference ?? null},${b.data.notes ?? null},${b.data.freightTotal ?? 0},${b.data.otherCostsTotal ?? 0},${s.identityId},${s.identityId}) returning *`); return row; }); if (result === 'supplier') return reply.code(404).send({ error: 'supplier_not_found' }); await service.auditResource(s, 'purchase_order.created', 'purchase_order', result.id); return reply.code(201).send(result); });
 app.patch('/purchase-orders/:id', async (req, reply) => { const p = params.safeParse(req.params), b = updateSchema.safeParse(req.body); if (!p.success || !b.success || !Object.keys(b.data).length) return reply.code(400).send({ error: 'invalid_request' }); const s = await auth(req, reply); if (!s || !await allow(reply, s, 'purchase_orders.update')) return; const result = await service.withAuthenticatedTenant(s, async (tx) => { const [old] = await tx.execute(sql`select status from purchase_orders where id=${p.data.id} for update`); if (!old) return 'missing'; if (old.status !== 'draft') return 'locked'; const [row] = await tx.execute(sql`update purchase_orders set expected_date=case when ${'expectedDate' in b.data} then ${b.data.expectedDate ?? null} else expected_date end,supplier_reference=case when ${'supplierReference' in b.data} then ${b.data.supplierReference ?? null} else supplier_reference end,notes=case when ${'notes' in b.data} then ${b.data.notes ?? null} else notes end,freight_total=coalesce(${b.data.freightTotal ?? null},freight_total),other_costs_total=coalesce(${b.data.otherCostsTotal ?? null},other_costs_total),total=round(subtotal-discount_total+coalesce(${b.data.freightTotal ?? null},freight_total)+coalesce(${b.data.otherCostsTotal ?? null},other_costs_total),2),updated_by_identity_id=${s.identityId},updated_at=now() where id=${p.data.id} returning *`); return row; }); if (result === 'missing') return reply.code(404).send({ error: 'not_found' }); if (result === 'locked') return reply.code(409).send({ error: 'purchase_order_not_editable' }); await service.auditResource(s, 'purchase_order.updated', 'purchase_order', p.data.id); return result; });
 app.get('/purchase-orders/:id/items', async (req, reply) => { const p = params.safeParse(req.params); if (!p.success) return reply.code(400).send({ error: 'invalid_request' }); const s = await auth(req, reply); if (!s || !await allow(reply, s, 'purchase_orders.read')) return; const found = await order(s, p.data.id); return found ? found.items : reply.code(404).send({ error: 'not_found' }); });
 app.post('/purchase-orders/:id/items', async (req, reply) => { const p = params.safeParse(req.params), b = itemCreate.safeParse(req.body); if (!p.success || !b.success || b.data.discount > b.data.quantity * b.data.unitCost) return reply.code(400).send({ error: 'invalid_request' }); const s = await auth(req, reply); if (!s || !await allow(reply, s, 'purchase_orders.update')) return; const result = await service.withAuthenticatedTenant(s, async (tx) => { const [po] = await tx.execute(sql`select status from purchase_orders where id=${p.data.id}`); if (!po) return 'order'; if (po.status !== 'draft') return 'locked'; const [part] = await tx.execute(sql`select id,description from inventory_parts where id=${b.data.inventoryPartId} and status='active'`); if (!part) return 'part'; const [row] = await tx.execute(sql`insert into purchase_order_items(tenant_id,purchase_order_id,inventory_part_id,description,quantity,unit_cost,discount,notes) values(${s.activeTenantId!},${p.data.id},${b.data.inventoryPartId},${b.data.description ?? part.description},${b.data.quantity},${b.data.unitCost},${b.data.discount},${b.data.notes ?? null}) returning *`); return row; }); if (result === 'order') return reply.code(404).send({ error: 'not_found' }); if (result === 'locked') return reply.code(409).send({ error: 'purchase_order_not_editable' }); if (result === 'part') return reply.code(404).send({ error: 'inventory_part_not_found' }); await service.auditResource(s, 'purchase_order_item.created', 'purchase_order', p.data.id, { inventoryPartId: b.data.inventoryPartId }); return reply.code(201).send(result); });
 app.patch('/purchase-orders/:id/items/:itemId', async (req, reply) => { const p = z.object({ id, itemId: id }).safeParse(req.params), b = itemUpdate.safeParse(req.body); if (!p.success || !b.success || !Object.keys(b.data).length) return reply.code(400).send({ error: 'invalid_request' }); const s = await auth(req, reply); if (!s || !await allow(reply, s, 'purchase_orders.update')) return; const result = await service.withAuthenticatedTenant(s, async (tx) => { const [old] = await tx.execute(sql`select i.*,p.status from purchase_order_items i join purchase_orders p on p.id=i.purchase_order_id where i.id=${p.data.itemId} and i.purchase_order_id=${p.data.id}`); if (!old) return 'missing'; if (old.status !== 'draft') return 'locked'; const quantity = b.data.quantity ?? Number(old.quantity), unitCost = b.data.unitCost ?? Number(old.unit_cost), discount = b.data.discount ?? Number(old.discount); if (discount > quantity * unitCost) return 'invalid'; const [row] = await tx.execute(sql`update purchase_order_items set description=coalesce(${b.data.description ?? null},description),quantity=${quantity},unit_cost=${unitCost},discount=${discount},notes=case when ${'notes' in b.data} then ${b.data.notes ?? null} else notes end,updated_at=now() where id=${p.data.itemId} and purchase_order_id=${p.data.id} returning *`); return row; }); if (result === 'missing') return reply.code(404).send({ error: 'not_found' }); if (result === 'locked') return reply.code(409).send({ error: 'purchase_order_not_editable' }); if (result === 'invalid') return reply.code(400).send({ error: 'invalid_request' }); await service.auditResource(s, 'purchase_order_item.updated', 'purchase_order', p.data.id); return result; });
 app.delete('/purchase-orders/:id/items/:itemId', async (req, reply) => { const p = z.object({ id, itemId: id }).safeParse(req.params); if (!p.success) return reply.code(400).send({ error: 'invalid_request' }); const s = await auth(req, reply); if (!s || !await allow(reply, s, 'purchase_orders.update')) return; const result = await service.withAuthenticatedTenant(s, async (tx) => { const [po] = await tx.execute(sql`select status from purchase_orders where id=${p.data.id}`); if (!po) return 'missing'; if (po.status !== 'draft') return 'locked'; const [row] = await tx.execute(sql`delete from purchase_order_items where id=${p.data.itemId} and purchase_order_id=${p.data.id} returning id`); return row ?? 'missing'; }); if (result === 'missing') return reply.code(404).send({ error: 'not_found' }); if (result === 'locked') return reply.code(409).send({ error: 'purchase_order_not_editable' }); await service.auditResource(s, 'purchase_order_item.deleted', 'purchase_order', p.data.id); return { deleted: true }; });
 app.post('/purchase-orders/:id/approve', async (req, reply) => { const p = params.safeParse(req.params); if (!p.success) return reply.code(400).send({ error: 'invalid_request' }); const s = await auth(req, reply); if (!s || !await allow(reply, s, 'purchase_orders.approve')) return; const result = await service.withAuthenticatedTenant(s, async (tx) => { const [old] = await tx.execute(sql`select status from purchase_orders where id=${p.data.id} for update`); if (!old) return 'missing'; if (!transitions[old.status].includes('approved')) return 'transition'; const [row] = await tx.execute(sql`update purchase_orders set status='approved',updated_by_identity_id=${s.identityId},updated_at=now() where id=${p.data.id} returning *`); return row; }); if (result === 'missing') return reply.code(404).send({ error: 'not_found' }); if (result === 'transition') return reply.code(409).send({ error: 'invalid_status_transition' }); await service.auditResource(s, 'purchase_order.approved', 'purchase_order', p.data.id); return result; });
 app.post('/purchase-orders/:id/cancel', async (req, reply) => { const p = params.safeParse(req.params); if (!p.success) return reply.code(400).send({ error: 'invalid_request' }); const s = await auth(req, reply); if (!s || !await allow(reply, s, 'purchase_orders.update')) return; const result = await service.withAuthenticatedTenant(s, async (tx) => { const [old] = await tx.execute(sql`select status from purchase_orders where id=${p.data.id} for update`); if (!old) return 'missing'; if (!transitions[old.status].includes('cancelled')) return 'transition'; const [row] = await tx.execute(sql`update purchase_orders set status='cancelled',updated_by_identity_id=${s.identityId},updated_at=now() where id=${p.data.id} returning *`); return row; }); if (result === 'missing') return reply.code(404).send({ error: 'not_found' }); if (result === 'transition') return reply.code(409).send({ error: 'invalid_status_transition' }); await service.auditResource(s, 'purchase_order.cancelled', 'purchase_order', p.data.id); return result; });
}
