// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
import type { FastifyInstance,FastifyReply,FastifyRequest } from 'fastify'; import { sql } from 'drizzle-orm'; import { z } from 'zod'; import type { AuthService,AuthSession,ResourceScope } from '../auth/service.js'; import { requirePermission } from '../auth/service.js';
const id=z.string().uuid(),params=z.object({id});
const optionalId=id.nullable().optional(),optionalText=(max:number)=>z.string().trim().max(max).nullable().optional();
const partCreate=z.object({sku:z.string().trim().min(1).max(80),description:z.string().trim().min(1).max(300),categoryId:optionalId,brandId:optionalId,unit:z.string().trim().min(1).max(20),barcodeEan:z.string().trim().regex(/^[0-9]{8,14}$/).nullable().optional(),referenceCost:z.coerce.number().nonnegative().nullable().optional(),referencePrice:z.coerce.number().nonnegative().nullable().optional(),minimumStock:z.coerce.number().nonnegative().default(0),defaultLocation:optionalText(120),ncm:z.string().trim().regex(/^[0-9]{8}$/).nullable().optional(),cest:z.string().trim().regex(/^[0-9]{7}$/).nullable().optional(),origin:z.enum(['0','1','2','3','4','5','6','7','8']).nullable().optional(),defaultCfop:z.string().trim().regex(/^[0-9]{4}$/).nullable().optional()}).strict();
const partUpdate=partCreate.partial().extend({status:z.enum(['active','inactive']).optional()}).strict();
const partList=z.object({search:z.string().trim().max(100).optional(),sku:z.string().trim().max(80).optional(),categoryId:id.optional(),brandId:id.optional(),status:z.enum(['active','inactive']).optional(),page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(20),order:z.enum(['newest','oldest','sku_asc','sku_desc']).default('sku_asc')}).strict();
const catalogCreate=z.object({name:z.string().trim().min(1).max(120)}).strict();
const catalogUpdate=z.object({name:z.string().trim().min(1).max(120).optional(),status:z.enum(['active','inactive']).optional()}).strict();
const moveSchema=z.object({partId:id,branchId:id.optional(),type:z.enum(['entry','exit','adjustment_in','adjustment_out']),quantity:z.coerce.number().positive(),reason:z.string().trim().min(1).max(1000)}).strict();
const movementList=z.object({partId:id.optional(),branchId:id.optional(),type:z.enum(['entry','exit','adjustment_in','adjustment_out']).optional(),from:z.string().datetime().optional(),to:z.string().datetime().optional(),page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(20),order:z.enum(['newest','oldest']).default('newest')}).strict();
const scope=(s:AuthSession):ResourceScope=>s.activeBranchId?{companyId:s.activeCompanyId!,branchId:s.activeBranchId}:s.activeCompanyId?{companyId:s.activeCompanyId}:{requireTenant:true};
type DatabaseError={code?:string;cause?:{code?:string}};
const databaseError=(e:unknown):DatabaseError=>typeof e==='object'&&e!==null?e as DatabaseError:{};
const duplicate=(e:unknown)=>databaseError(e).code==='23505'||databaseError(e).cause?.code==='23505';
const dbCode=(e:unknown)=>databaseError(e).code??databaseError(e).cause?.code;
export function registerInventoryRoutes(app:FastifyInstance,service:AuthService){
 async function auth(req:FastifyRequest,reply:FastifyReply){const s=await service.session(req.cookies.vetoros_session);if(!s){reply.code(401).send({error:'unauthorized'});return;}if(!s.activeTenantId||!s.activeCompanyId||!s.activeBranchId){reply.code(409).send({error:'operational_context_required'});return;}return s;}
 async function allow(reply:FastifyReply,s:AuthSession,p:string,target:ResourceScope=scope(s)){try{await requirePermission(service,s,p,target);return true;}catch{reply.code(403).send({error:'forbidden'});return false;}}
 app.get('/inventory/parts',async(req,reply)=>{const q=partList.safeParse(req.query);if(!q.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'inventory.read'))return;const offset=(q.data.page-1)*q.data.pageSize,term=q.data.search?`%${q.data.search}%`:null,ordering=q.data.order==='oldest'?sql`p.created_at asc`:q.data.order==='newest'?sql`p.created_at desc`:q.data.order==='sku_desc'?sql`p.sku desc`:sql`p.sku asc`;const rows=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`select p.*,pc.name category_name,pb.name brand_name,coalesce(b.quantity,0) balance,count(*) over()::int total from inventory_parts p left join product_categories pc on pc.id=p.category_id left join product_brands pb on pb.id=p.brand_id left join stock_balances b on b.part_id=p.id and b.branch_id=${s.activeBranchId!} where (${q.data.status??null}::text is null or p.status=${q.data.status??null}) and (${q.data.sku??null}::text is null or p.sku=${q.data.sku??null}) and (${q.data.categoryId??null}::uuid is null or p.category_id=${q.data.categoryId??null}) and (${q.data.brandId??null}::uuid is null or p.brand_id=${q.data.brandId??null}) and (${term}::text is null or p.sku ilike ${term} or p.description ilike ${term} or p.barcode_ean ilike ${term} or pc.name ilike ${term} or pb.name ilike ${term}) order by ${ordering} limit ${q.data.pageSize} offset ${offset}`));return{items:rows.map(r=>Object.fromEntries(Object.entries(r).filter(([k])=>k!=='total'))),page:q.data.page,pageSize:q.data.pageSize,total:Number(rows[0]?.total??0)};});
 app.post('/inventory/parts',async(req,reply)=>{const b=partCreate.safeParse(req.body);if(!b.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'inventory.create'))return;try{const [row]=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`insert into inventory_parts(tenant_id,sku,description,category_id,brand_id,unit,barcode_ean,reference_cost,reference_price,minimum_stock,default_location,ncm,created_by_identity_id,updated_by_identity_id) values(${s.activeTenantId!},${b.data.sku},${b.data.description},${b.data.categoryId??null},${b.data.brandId??null},${b.data.unit},${b.data.barcodeEan??null},${b.data.referenceCost??null},${b.data.referencePrice??null},${b.data.minimumStock},${b.data.defaultLocation??null},${b.data.ncm??null},${s.identityId},${s.identityId}) returning *`));await service.auditResource(s,'inventory_part.created','inventory_part',row!.id);return reply.code(201).send(row);}catch(e){if(duplicate(e))return reply.code(409).send({error:'sku_or_barcode_already_exists'});if(dbCode(e)==='23503')return reply.code(400).send({error:'invalid_category_or_brand'});throw e;}});
 app.get('/inventory/parts/:id',async(req,reply)=>{const p=params.safeParse(req.params);if(!p.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'inventory.read'))return;const [row]=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`select p.*,pc.name category_name,pb.name brand_name,coalesce(b.quantity,0) balance from inventory_parts p left join product_categories pc on pc.id=p.category_id left join product_brands pb on pb.id=p.brand_id left join stock_balances b on b.part_id=p.id and b.branch_id=${s.activeBranchId!} where p.id=${p.data.id}`));return row??reply.code(404).send({error:'not_found'});});
 app.patch('/inventory/parts/:id/fiscal',async(req,reply)=>{const p=params.safeParse(req.params),b=z.object({cest:z.string().regex(/^[0-9]{7}$/).nullable().optional(),origin:z.enum(['0','1','2','3','4','5','6','7','8']).nullable().optional(),defaultCfop:z.string().regex(/^[0-9]{4}$/).nullable().optional()}).strict().safeParse(req.body);if(!p.success||!b.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'inventory.update'))return;const[row]=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`update inventory_parts set cest=case when ${'cest'in b.data} then ${b.data.cest??null} else cest end,origin=case when ${'origin'in b.data} then ${b.data.origin??null} else origin end,default_cfop=case when ${'defaultCfop'in b.data} then ${b.data.defaultCfop??null} else default_cfop end,updated_by_identity_id=${s.identityId},updated_at=now() where id=${p.data.id} returning *`));return row??reply.code(404).send({error:'not_found'});});
 app.patch('/inventory/parts/:id',async(req,reply)=>{const p=params.safeParse(req.params),b=partUpdate.safeParse(req.body);if(!p.success||!b.success||!Object.keys(b.data).length)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'inventory.update'))return;try{const [row]=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`update inventory_parts set sku=coalesce(${b.data.sku??null},sku),description=coalesce(${b.data.description??null},description),category_id=case when ${'categoryId'in b.data} then ${b.data.categoryId??null} else category_id end,brand_id=case when ${'brandId'in b.data} then ${b.data.brandId??null} else brand_id end,unit=coalesce(${b.data.unit??null},unit),barcode_ean=case when ${'barcodeEan'in b.data} then ${b.data.barcodeEan??null} else barcode_ean end,reference_cost=case when ${'referenceCost'in b.data} then ${b.data.referenceCost??null} else reference_cost end,reference_price=case when ${'referencePrice'in b.data} then ${b.data.referencePrice??null} else reference_price end,minimum_stock=coalesce(${b.data.minimumStock??null},minimum_stock),default_location=case when ${'defaultLocation'in b.data} then ${b.data.defaultLocation??null} else default_location end,ncm=case when ${'ncm'in b.data} then ${b.data.ncm??null} else ncm end,status=coalesce(${b.data.status??null},status),updated_by_identity_id=${s.identityId},updated_at=now() where id=${p.data.id} returning *`));if(!row)return reply.code(404).send({error:'not_found'});await service.auditResource(s,b.data.status?'inventory_part.status_changed':'inventory_part.updated','inventory_part',p.data.id);return row;}catch(e){if(duplicate(e))return reply.code(409).send({error:'sku_or_barcode_already_exists'});if(dbCode(e)==='23503')return reply.code(400).send({error:'invalid_category_or_brand'});throw e;}});
 for(const catalog of [{path:'categories',table:sql.raw('product_categories'),resource:'product_category'},{path:'brands',table:sql.raw('product_brands'),resource:'product_brand'}] as const){
  app.get(`/inventory/${catalog.path}`,async(req,reply)=>{const s=await auth(req,reply);if(!s||!await allow(reply,s,'inventory.read'))return;return service.withAuthenticatedTenant(s,tx=>tx.execute(sql`select id,name,status from ${catalog.table} order by status,name`));});
  app.post(`/inventory/${catalog.path}`,async(req,reply)=>{const b=catalogCreate.safeParse(req.body);if(!b.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'inventory.create'))return;try{const[row]=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`insert into ${catalog.table}(tenant_id,name,created_by_identity_id,updated_by_identity_id) values(${s.activeTenantId!},${b.data.name},${s.identityId},${s.identityId}) returning *`));await service.auditResource(s,`${catalog.resource}.created`,catalog.resource,row!.id);return reply.code(201).send(row);}catch(e){if(duplicate(e))return reply.code(409).send({error:'name_already_exists'});throw e;}});
  app.patch(`/inventory/${catalog.path}/:id`,async(req,reply)=>{const p=params.safeParse(req.params),b=catalogUpdate.safeParse(req.body);if(!p.success||!b.success||!Object.keys(b.data).length)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'inventory.update'))return;try{const[row]=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`update ${catalog.table} set name=coalesce(${b.data.name??null},name),status=coalesce(${b.data.status??null},status),updated_by_identity_id=${s.identityId},updated_at=now() where id=${p.data.id} returning *`));if(!row)return reply.code(404).send({error:'not_found'});await service.auditResource(s,`${catalog.resource}.updated`,catalog.resource,p.data.id);return row;}catch(e){if(duplicate(e))return reply.code(409).send({error:'name_already_exists'});throw e;}});
 }
 app.get('/inventory/balances',async(req,reply)=>{const q=z.object({partId:id.optional(),branchId:id.optional()}).strict().safeParse(req.query);if(!q.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'inventory.read'))return;const branch=q.data.branchId??s.activeBranchId!;if(branch!==s.activeBranchId)return reply.code(403).send({error:'forbidden'});return service.withAuthenticatedTenant(s,tx=>tx.execute(sql`select b.*,p.sku,p.description,p.unit from stock_balances b join inventory_parts p on p.id=b.part_id where b.branch_id=${branch} and (${q.data.partId??null}::uuid is null or b.part_id=${q.data.partId??null}) order by p.sku`));});
 app.get('/inventory/movements',async(req,reply)=>{const q=movementList.safeParse(req.query);if(!q.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'inventory.read'))return;const branch=q.data.branchId??s.activeBranchId!;if(branch!==s.activeBranchId)return reply.code(403).send({error:'forbidden'});const offset=(q.data.page-1)*q.data.pageSize,ordering=q.data.order==='oldest'?sql`m.created_at asc`:sql`m.created_at desc`;const rows=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`select m.*,p.sku,p.description,count(*) over()::int total from stock_movements m join inventory_parts p on p.id=m.part_id where m.branch_id=${branch} and (${q.data.partId??null}::uuid is null or m.part_id=${q.data.partId??null}) and (${q.data.type??null}::text is null or m.type=${q.data.type??null}) and (${q.data.from??null}::timestamptz is null or m.created_at>=${q.data.from??null}) and (${q.data.to??null}::timestamptz is null or m.created_at<=${q.data.to??null}) order by ${ordering} limit ${q.data.pageSize} offset ${offset}`));return{items:rows.map(r=>Object.fromEntries(Object.entries(r).filter(([k])=>k!=='total'))),page:q.data.page,pageSize:q.data.pageSize,total:Number(rows[0]?.total??0)};});
 app.post('/inventory/movements',async(req,reply)=>{const b=moveSchema.safeParse(req.body);if(!b.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply),branch=b.data.branchId??s?.activeBranchId;if(!s)return;if(branch!==s.activeBranchId)return reply.code(400).send({error:'invalid_branch'});if(!await allow(reply,s,'inventory.move',{companyId:s.activeCompanyId!,branchId:branch!}))return;try{const [result]=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`select * from record_stock_movement(${s.activeCompanyId!},${branch!},${b.data.partId},${b.data.type},${b.data.quantity},${b.data.reason})`));await service.auditResource(s,'stock_movement.created','stock_movement',result!.movement_id,{type:b.data.type,partId:b.data.partId,quantity:b.data.quantity});return reply.code(201).send(result);}catch(e){const code=dbCode(e);if(code==='23514')return reply.code(409).send({error:'insufficient_stock'});if(code==='23503')return reply.code(404).send({error:'part_or_branch_not_found'});if(code==='22023')return reply.code(400).send({error:'invalid_request'});throw e;}});
}
