create table supplier_number_counters(tenant_id uuid primary key references tenants(id),last_number bigint not null default 0 check(last_number>=0),updated_at timestamptz not null default now());
create table suppliers(
 id uuid primary key default gen_random_uuid(),tenant_id uuid not null references tenants(id),supplier_number bigint not null,person_type text not null,legal_name text not null,trade_name text,document_type text,document_normalized text,state_registration text,municipal_registration text,notes text,status text not null default 'active',created_by_identity_id uuid references identities(id),updated_by_identity_id uuid references identities(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 unique(tenant_id,id),unique(tenant_id,supplier_number),check(person_type in('individual','company')),check(length(legal_name) between 1 and 200),check(status in('active','inactive')),
 check((document_normalized is null and document_type is null) or(document_type='cpf' and person_type='individual' and document_normalized~'^[0-9]{11}$')or(document_type='cnpj' and person_type='company' and document_normalized~'^[0-9]{14}$'))
);
create unique index suppliers_document_uq on suppliers(tenant_id,document_type,document_normalized) where document_normalized is not null;create index suppliers_name_idx on suppliers(tenant_id,lower(legal_name) text_pattern_ops);create index suppliers_number_idx on suppliers(tenant_id,supplier_number);
create table supplier_addresses(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,supplier_id uuid not null,address_type text not null default 'commercial',postal_code text,street text not null,number text,complement text,district text,city text not null,state char(2),country char(2) not null default 'BR',is_primary boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,id),foreign key(tenant_id,supplier_id) references suppliers(tenant_id,id) on delete restrict,check(address_type in('commercial','billing','shipping','other')));
create unique index supplier_addresses_primary_uq on supplier_addresses(tenant_id,supplier_id) where is_primary;create index supplier_addresses_supplier_idx on supplier_addresses(tenant_id,supplier_id);
create table supplier_contacts(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,supplier_id uuid not null,contact_type text not null,label text,value text not null,value_normalized text not null,is_primary boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,id),foreign key(tenant_id,supplier_id) references suppliers(tenant_id,id) on delete restrict,check(contact_type in('phone','mobile','whatsapp','email','other')));
create unique index supplier_contacts_primary_type_uq on supplier_contacts(tenant_id,supplier_id,contact_type) where is_primary;create index supplier_contacts_supplier_idx on supplier_contacts(tenant_id,supplier_id);create index supplier_contacts_value_idx on supplier_contacts(tenant_id,value_normalized text_pattern_ops);
alter table supplier_number_counters enable row level security;alter table supplier_number_counters force row level security;create policy supplier_counters_tenant on supplier_number_counters using(tenant_id=vetoros_current_tenant_id())with check(tenant_id=vetoros_current_tenant_id());
alter table suppliers enable row level security;alter table suppliers force row level security;create policy suppliers_tenant on suppliers using(tenant_id=vetoros_current_tenant_id())with check(tenant_id=vetoros_current_tenant_id());
alter table supplier_addresses enable row level security;alter table supplier_addresses force row level security;create policy supplier_addresses_tenant on supplier_addresses using(tenant_id=vetoros_current_tenant_id())with check(tenant_id=vetoros_current_tenant_id());
alter table supplier_contacts enable row level security;alter table supplier_contacts force row level security;create policy supplier_contacts_tenant on supplier_contacts using(tenant_id=vetoros_current_tenant_id())with check(tenant_id=vetoros_current_tenant_id());
grant select,insert,update on supplier_number_counters,suppliers,supplier_addresses,supplier_contacts to vetoros_runtime;
