'use client';
import { use, useEffect, useState } from 'react';
import Link from 'next/link';
import { api } from '../../../../../lib/api';
import { formatCurrency, formatDate } from '../../../../../lib/format';

type Order = { id:string; order_number:number; status:string; company_name:string; branch_name:string; customer_name:string; asset_identifier:string|null; reported_problem:string; diagnosis:string|null; executed_solution:string|null; technical_notes:string|null; subtotal:number; discounts:number; total:number; items:Array<{description:string;quantity:string;unit_price:string;total_amount:string}> };
type Payment = { amount:string; payment_method_name:string; refunded:boolean };
type Receivable = { original_amount:string; balance:string; derived_status:string };

export default function ServiceOrderPrintPage({ params }: { params: Promise<{ id:string }> }) {
  const { id } = use(params);
  const [data,setData]=useState<{order:Order;payments:Payment[];receivables:Receivable[]}>();
  useEffect(()=>{void (async()=>{const [o,p,r]=await Promise.all([api(`/service-orders/${id}`),api(`/payments?serviceOrderId=${id}&pageSize=100`),api(`/receivables?serviceOrderId=${id}&pageSize=100`)]);if(o.ok)setData({order:await o.json(),payments:p.ok?(await p.json()).items:[],receivables:r.ok?(await r.json()).items:[]});})();},[id]);
  if(!data)return <p className="p-8 text-sm text-slate-500">Carregando comprovante…</p>;
  const {order,payments,receivables}=data; const received=payments.filter(p=>!p.refunded).reduce((n,p)=>n+Number(p.amount),0); const pending=receivables.reduce((n,r)=>n+Number(r.balance),Math.max(order.total-received,0));
  return <main className="mx-auto max-w-3xl p-8 text-slate-900 print:p-0"><div className="mb-6 flex items-center justify-between print:hidden"><Link href={`/app/service-orders/${id}`} className="text-sm text-blue-700">← Voltar para OS</Link><button onClick={()=>window.print()} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Imprimir</button></div><header className="border-b-2 border-slate-900 pb-4"><p className="text-xs font-semibold tracking-widest">ORDEM DE SERVIÇO / COMPROVANTE NÃO FISCAL</p><h1 className="mt-2 text-2xl font-bold">OS #{order.order_number}</h1><p className="text-sm">{order.company_name} · {order.branch_name}</p><p className="text-sm">Situação: {order.status} · Emissão: {formatDate(new Date().toISOString())}</p></header><section className="grid gap-3 border-b py-4 text-sm sm:grid-cols-2"><p><strong>Cliente:</strong> {order.customer_name}</p><p><strong>Equipamento:</strong> {order.asset_identifier||'—'}</p><p className="sm:col-span-2"><strong>Defeito relatado:</strong> {order.reported_problem||'—'}</p><p><strong>Diagnóstico:</strong> {order.diagnosis||'—'}</p><p><strong>Solução:</strong> {order.executed_solution||'—'}</p></section><section className="py-4"><h2 className="mb-2 font-semibold">Serviços e peças</h2><table className="w-full text-sm"><thead><tr className="border-b text-left"><th>Descrição</th><th>Qtd.</th><th className="text-right">Total</th></tr></thead><tbody>{order.items.map((item,i)=><tr key={i} className="border-b"><td className="py-2">{item.description}</td><td>{item.quantity}</td><td className="text-right">{formatCurrency(item.total_amount)}</td></tr>)}</tbody></table><p className="mt-3 text-right text-sm">Subtotal: {formatCurrency(order.subtotal)} · Descontos: {formatCurrency(order.discounts)} · <strong>Total: {formatCurrency(order.total)}</strong></p></section><section className="grid gap-3 border-t py-4 text-sm sm:grid-cols-2"><div><h2 className="font-semibold">Pagamentos</h2>{payments.filter(p=>!p.refunded).map((p,i)=><p key={i}>{p.payment_method_name}: {formatCurrency(p.amount)}</p>)}{!payments.length&&<p>Não informado.</p>}</div><div><h2 className="font-semibold">Saldo pendente</h2><p>{formatCurrency(pending)}</p><p>Situação financeira: {receivables.length?(pending<=0.005?'Quitado':'Em aberto'):'Sem parcelamento'}</p></div></section><footer className="mt-8 border-t pt-4 text-xs text-slate-600">Documento operacional sem validade fiscal. Não substitui NFC-e, NF-e ou NFS-e.</footer></main>;
}
