import{readFile}from'node:fs/promises';import{describe,expect,it}from'vitest';const m=await readFile(new URL('../migrations/0014_purchase_receipts.sql',import.meta.url),'utf8');
describe('COM-03 purchase receipts database contract',()=>{
 it('uses dedicated tables with a transactional counter, scoped to Tenant/Company/Branch',()=>{expect(m).toContain('create table purchase_receipt_number_counters');expect(m).toContain('create table purchase_receipts');expect(m).toContain('create table purchase_receipt_items');expect(m).toContain('foreign key(tenant_id,company_id) references companies(tenant_id,id)');expect(m).toContain('foreign key(tenant_id,company_id,branch_id) references branches(tenant_id,company_id,id)');});
 it('requires an existing same-tenant purchase order and restricts the status machine',()=>{expect(m).toContain('foreign key(tenant_id,purchase_order_id) references purchase_orders(tenant_id,id)');expect(m).toContain("check(status in('draft','confirmed','cancelled'))");expect(m).not.toContain("'received'");expect(m).not.toContain("'partially_received'");});
 it('guarantees at the database level that a receipt item belongs to the same order as its receipt',()=>{expect(m).toContain('purchase_order_items_tenant_order_id_uq unique(tenant_id,purchase_order_id,id)');expect(m).toContain('unique(tenant_id,id,purchase_order_id)');expect(m).toContain('foreign key(tenant_id,purchase_receipt_id,purchase_order_id) references purchase_receipts(tenant_id,id,purchase_order_id)');expect(m).toContain('foreign key(tenant_id,purchase_order_id,purchase_order_item_id) references purchase_order_items(tenant_id,purchase_order_id,id)');});
 it('requires a same-tenant inventory part per item and a positive received quantity',()=>{expect(m).toContain('foreign key(tenant_id,inventory_part_id) references inventory_parts(tenant_id,id)');expect(m).toContain('check(quantity>0)');});
 it('forces fail-closed RLS on every new table',()=>{expect(m.match(/force row level security/g)).toHaveLength(3);expect(m.match(/vetoros_current_tenant_id\(\)/g)?.length).toBeGreaterThanOrEqual(6);});
 it('links stock movements to their receipt origin without touching prior movement semantics',()=>{expect(m).toContain('add column purchase_receipt_id uuid');expect(m).toContain('add column purchase_receipt_item_id uuid');expect(m).toContain('references purchase_receipts(tenant_id,id)');expect(m).toContain('references purchase_receipt_items(tenant_id,id)');});
 it('reuses EST-01 ledger/balance logic via a backward-compatible signature extension',()=>{expect(m).toContain('drop function if exists record_stock_movement(uuid,uuid,uuid,text,numeric,text)');expect(m).toContain('create function record_stock_movement');expect(m).toContain('p_purchase_receipt_id uuid default null');expect(m).toContain('p_purchase_receipt_item_id uuid default null');expect(m).toContain('on conflict(tenant_id,branch_id,part_id) do nothing');});
 it('confirms atomically: locks order items before validating pending quantity, in a stable order',()=>{expect(m).toContain('create function confirm_purchase_receipt');expect(m).toContain('security definer');expect(m).toContain('order by id for update');expect(m).toContain('v_received+v_row.this_quantity>v_row.ordered_quantity');});
 it('makes re-confirmation idempotent instead of duplicating stock',()=>{expect(m).toContain("if v_receipt.status='confirmed' then return query select v_receipt.id,v_receipt.status,v_receipt.confirmed_at,true");});
 it('names function outputs to avoid ambiguity with same-named table columns',()=>{expect(m).toContain('returns table(receipt_id uuid,receipt_status text,confirmed_at timestamptz,idempotent boolean)');expect(m).not.toContain('returns table(id uuid,status text');});
 it('rejects confirmation of a cancelled receipt or a non-approved purchase order',()=>{expect(m).toContain("if v_receipt.status='cancelled' then raise exception");expect(m).toContain("if v_order.status<>'approved' then raise exception");});
 it('does not grant delete on the receipt header and stays out of fiscal/payables scope',()=>{expect(m).not.toMatch(/grant[^;]*delete[^;]*purchase_receipts\b/);expect(m).not.toContain('accounts_payable');expect(m).not.toContain('nfe');});
});
