import{readFile}from'node:fs/promises';import{describe,expect,it}from'vitest';const m=await readFile(new URL('../migrations/0015_purchase_returns.sql',import.meta.url),'utf8');
describe('COM-04 purchase returns database contract',()=>{
 it('uses dedicated tables with a transactional counter, scoped to Tenant/Company/Branch',()=>{expect(m).toContain('create table purchase_return_number_counters');expect(m).toContain('create table purchase_returns');expect(m).toContain('create table purchase_return_items');expect(m).toContain('foreign key(tenant_id,company_id) references companies(tenant_id,id)');expect(m).toContain('foreign key(tenant_id,company_id,branch_id) references branches(tenant_id,company_id,id)');});
 it('requires an existing same-tenant confirmed-origin receipt and restricts the status machine',()=>{expect(m).toContain('foreign key(tenant_id,purchase_receipt_id) references purchase_receipts(tenant_id,id)');expect(m).toContain("check(status in('draft','confirmed','cancelled'))");});
 it('guarantees at the database level that a return item belongs to the same receipt as its return',()=>{expect(m).toContain('purchase_receipt_items_tenant_receipt_id_uq unique(tenant_id,purchase_receipt_id,id)');expect(m).toContain('unique(tenant_id,id,purchase_receipt_id)');expect(m).toContain('foreign key(tenant_id,purchase_return_id,purchase_receipt_id) references purchase_returns(tenant_id,id,purchase_receipt_id)');expect(m).toContain('foreign key(tenant_id,purchase_receipt_id,purchase_receipt_item_id) references purchase_receipt_items(tenant_id,purchase_receipt_id,id)');});
 it('guarantees at the database level that the returned part matches the received part',()=>{expect(m).toContain('purchase_receipt_items_tenant_id_part_uq unique(tenant_id,id,inventory_part_id)');expect(m).toContain('foreign key(tenant_id,purchase_receipt_item_id,inventory_part_id) references purchase_receipt_items(tenant_id,id,inventory_part_id)');});
 it('requires a same-tenant inventory part and a positive returned quantity',()=>{expect(m).toContain('foreign key(tenant_id,inventory_part_id) references inventory_parts(tenant_id,id)');expect(m).toContain('check(quantity>0)');});
 it('forces fail-closed RLS on every new table',()=>{expect(m.match(/force row level security/g)).toHaveLength(3);expect(m.match(/vetoros_current_tenant_id\(\)/g)?.length).toBeGreaterThanOrEqual(6);});
 it('links stock movements to their return origin, reusing the exit type instead of a bespoke one',()=>{expect(m).toContain('add column purchase_return_id uuid');expect(m).toContain('add column purchase_return_item_id uuid');expect(m).toContain('references purchase_returns(tenant_id,id)');expect(m).toContain('references purchase_return_items(tenant_id,id)');expect(m).not.toContain("'purchase_return'");});
 it('reuses EST-01/COM-03 ledger logic via a backward-compatible signature extension, replaced in place',()=>{expect(m).toContain('drop function if exists record_stock_movement(uuid,uuid,uuid,text,numeric,text,uuid,uuid)');expect(m).toContain('create function record_stock_movement');expect(m).toContain('p_purchase_return_id uuid default null');expect(m).toContain('p_purchase_return_item_id uuid default null');expect(m).toContain('on conflict(tenant_id,branch_id,part_id) do nothing');expect(m).toContain('insufficient stock');});
 it('confirms atomically: locks the receipt items before validating the returnable quantity, in a stable order',()=>{expect(m).toContain('create function confirm_purchase_return');expect(m).toContain('security definer');expect(m).toContain('order by id for update');expect(m).toContain('v_returned+v_row.this_quantity>v_row.received_quantity');});
 it('processes items in a stable part order before touching stock balances, to avoid deadlock',()=>{expect(m).toContain('order by ri.inventory_part_id');});
 it('makes re-confirmation idempotent instead of duplicating stock',()=>{expect(m).toContain("if v_return.status='confirmed' then return query select v_return.id,v_return.status,v_return.confirmed_at,true");});
 it('rejects confirmation of a cancelled return or a non-confirmed receipt, and names outputs to avoid ambiguity',()=>{expect(m).toContain("if v_return.status='cancelled' then raise exception");expect(m).toContain("if v_receipt.status<>'confirmed' then raise exception");expect(m).toContain('returns table(return_id uuid,return_status text,confirmed_at timestamptz,idempotent boolean)');});
 it('never grants direct write access to stock_balances, and does not touch purchase_orders.status',()=>{expect(m).not.toMatch(/grant[^;]*(insert|update|delete)[^;]*stock_balances/);expect(m).not.toContain('update purchase_orders set status');});
 it('does not grant delete on the return header and stays out of fiscal/payables scope',()=>{expect(m).not.toMatch(/grant[^;]*delete[^;]*purchase_returns\b/);expect(m).not.toContain('accounts_payable');expect(m).not.toContain('nfe');});
});
