import{readFile}from'node:fs/promises';import{describe,expect,it}from'vitest';const m=await readFile(new URL('../migrations/0013_purchase_orders.sql',import.meta.url),'utf8');
describe('COM-02 purchase orders database contract',()=>{
 it('uses dedicated tenant/company/branch tables with a transactional counter',()=>{expect(m).toContain('create table purchase_order_number_counters');expect(m).toContain('create table purchase_orders');expect(m).toContain('create table purchase_order_items');});
 it('scopes ownership to tenant, company and branch',()=>{expect(m).toContain('foreign key(tenant_id,company_id) references companies(tenant_id,id)');expect(m).toContain('foreign key(tenant_id,company_id,branch_id) references branches(tenant_id,company_id,id)');});
 it('requires an existing same-tenant supplier and restricts the status machine',()=>{expect(m).toContain('foreign key(tenant_id,supplier_id) references suppliers(tenant_id,id)');expect(m).toContain("check(status in('draft','approved','cancelled'))");expect(m).not.toContain('received');expect(m).not.toContain('partially_received');expect(m).not.toContain('invoiced');});
 it('requires an existing same-tenant inventory part per item and preserves a commercial snapshot',()=>{expect(m).toContain('foreign key(tenant_id,inventory_part_id) references inventory_parts(tenant_id,id)');expect(m).toContain('inventory_part_id uuid not null');expect(m).toContain('description text not null');});
 it('enforces unique sequential numbering per tenant',()=>{expect(m).toContain('unique(tenant_id,purchase_order_number)');});
 it('calculates item totals deterministically and forbids negative values',()=>{expect(m).toContain('numeric(14,3)');expect(m).toContain('numeric(14,2) generated always as (round(quantity*unit_cost-discount,2)) stored');expect(m).toContain('check(discount<=quantity*unit_cost)');expect(m).toContain('check(quantity>0)');expect(m).toContain('check(unit_cost>=0)');});
 it('keeps header totals non-negative and derived in the database',()=>{expect(m).toContain('check(total>=0)');expect(m).toContain('check(subtotal>=0)');expect(m).toContain('check(discount_total>=0)');expect(m).toContain('recompute_purchase_order_totals');expect(m).toContain('after insert or update or delete on purchase_order_items');});
 it('forces fail-closed RLS on every new table',()=>{expect(m.match(/force row level security/g)).toHaveLength(3);expect(m.match(/vetoros_current_tenant_id\(\)/g)?.length).toBeGreaterThanOrEqual(6);});
 it('does not grant delete on the header and stays out of receiving/stock/payables scope',()=>{expect(m).not.toMatch(/grant[^;]*delete[^;]*purchase_orders\b/);expect(m).not.toContain('stock_movements');expect(m).not.toContain('stock_balances');expect(m).not.toContain('accounts_payable');expect(m).not.toContain('purchase_receipts');});
});
