import{readFile}from'node:fs/promises';import{describe,expect,it}from'vitest';const m=await readFile(new URL('../migrations/0016_sales.sql',import.meta.url),'utf8');
describe('VEN-01 sales database contract',()=>{
 it('uses dedicated tables with a transactional counter, scoped to Tenant/Company/Branch',()=>{expect(m).toContain('create table sale_number_counters');expect(m).toContain('create table sales');expect(m).toContain('create table sale_items');expect(m).toContain('foreign key(tenant_id,company_id) references companies(tenant_id,id)');expect(m).toContain('foreign key(tenant_id,company_id,branch_id) references branches(tenant_id,company_id,id)');});
 it('makes the customer optional but same-tenant when present',()=>{expect(m).toContain('customer_id uuid,');expect(m).not.toContain('customer_id uuid not null');expect(m).toContain('foreign key(tenant_id,customer_id) references customers(tenant_id,id)');});
 it('restricts the status machine to draft/confirmed/cancelled',()=>{expect(m).toContain("check(status in('draft','confirmed','cancelled'))");expect(m).not.toContain("'received'");expect(m).not.toContain("'invoiced'");expect(m).not.toContain("'paid'");});
 it('requires an existing same-tenant inventory part only for part-typed items, and enforces the type/part correspondence',()=>{expect(m).toContain('foreign key(tenant_id,inventory_part_id) references inventory_parts(tenant_id,id)');expect(m).toContain("check(inventory_part_id is null or type='part')");expect(m).toContain("check(type in('service','part'))");});
 it('calculates item totals deterministically and forbids negative or over-discounted values',()=>{expect(m).toContain('numeric(14,3)');expect(m).toContain('numeric(14,2) generated always as (round(quantity*unit_price-discount_amount,2)) stored');expect(m).toContain('check(discount_amount<=quantity*unit_price)');expect(m).toContain('check(quantity>0)');expect(m).toContain('check(unit_price>=0)');});
 it('enforces unique sequential numbering per tenant',()=>{expect(m).toContain('unique(tenant_id,sale_number)');});
 it('forces fail-closed RLS on every new table',()=>{expect(m.match(/force row level security/g)).toHaveLength(3);expect(m.match(/vetoros_current_tenant_id\(\)/g)?.length).toBeGreaterThanOrEqual(6);});
 it('does not touch stock_movements/stock_balances and does not grant delete on the header',()=>{expect(m).not.toContain('stock_movements');expect(m).not.toContain('stock_balances');expect(m).not.toMatch(/grant[^;]*delete[^;]*\bsales\b/);});
 it('stays out of cash/receivables/fiscal scope',()=>{expect(m).not.toContain('accounts_receivable');expect(m).not.toContain('cash_register');expect(m).not.toContain('nfe');});
});
