import{readFile}from'node:fs/promises';import{describe,expect,it}from'vitest';const m=await readFile(new URL('../migrations/0017_sale_stock.sql',import.meta.url),'utf8');
describe('VEN-02 sale/stock integration database contract',()=>{
 it('links stock movements to their sale origin without touching prior movement semantics',()=>{expect(m).toContain('add column sale_id uuid');expect(m).toContain('add column sale_item_id uuid');expect(m).toContain('references sales(tenant_id,id)');expect(m).toContain('references sale_items(tenant_id,id)');});
 it('reuses the existing exit movement type instead of a bespoke sale-specific one',()=>{expect(m).not.toContain("'sale'");expect(m).not.toContain("'sale_exit'");expect(m).toContain("p_type not in ('entry','exit','adjustment_in','adjustment_out')");});
 it('structurally forbids more than one stock movement per sale item, independent of application logic',()=>{expect(m).toContain('create unique index stock_movements_sale_item_uq on stock_movements(sale_item_id) where sale_item_id is not null');});
 it('reuses EST-01/COM-03/COM-04 ledger logic via a backward-compatible signature extension, replaced in place',()=>{expect(m).toContain('drop function if exists record_stock_movement(uuid,uuid,uuid,text,numeric,text,uuid,uuid,uuid,uuid)');expect(m).toContain('create function record_stock_movement');expect(m).toContain('p_sale_id uuid default null');expect(m).toContain('p_sale_item_id uuid default null');expect(m).toContain('on conflict(tenant_id,branch_id,part_id) do nothing');expect(m).toContain('insufficient stock');});
 it('keeps the balance projection consistent: locks before validating, never allows a negative balance',()=>{expect(m).toContain('for update');expect(m).toContain('if v_balance+v_delta<0 then raise exception');expect(m).toContain("errcode='23514'");});
 it('grants only execute on the function, no direct write access to stock_balances',()=>{expect(m).not.toMatch(/grant[^;]*(insert|update|delete)[^;]*stock_balances/);expect(m).toContain('grant execute on function record_stock_movement');});
});
