import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import { sql } from 'drizzle-orm';
import { z } from 'zod';
import type { AuthService, AuthSession, ResourceScope } from '../auth/service.js';
import { requirePermission } from '../auth/service.js';
const id=z.string().uuid(); const params=z.object({id}).strict();
const asset=z.object({customerId:id,internalIdentifier:z.string().trim().min(1).max(80),category:z.string().trim().min(1).max(80),brand:z.string().trim().max(120).nullable().optional(),model:z.string().trim().max(120).nullable().optional(),serialNumber:z.string().trim().max(160).nullable().optional(),imei:z.string().trim().max(20).nullable().optional(),assetTag:z.string().trim().max(100).nullable().optional(),description:z.string().trim().max(1000).nullable().optional(),notes:z.string().trim().max(4000).nullable().optional(),status:z.enum(['active','inactive','retired']).default('active'),originCompanyId:id.nullable().optional(),originBranchId:id.nullable().optional(),identifiers:z.array(z.object({identifierType:z.string().trim().min(1).max(60),value:z.string().trim().min(1).max(200)}).strict()).max(20).optional()}).strict();
const update=asset.omit({customerId:true,originCompanyId:true,originBranchId:true,identifiers:true}).partial().strict(); const list=z.object({search:z.string().trim().max(100).optional(),customerId:id.optional(),category:z.string().trim().max(80).optional(),status:z.enum(['active','inactive','retired']).optional(),page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(20)}).strict(); const identifier=z.object({identifierType:z.string().trim().min(1).max(60),value:z.string().trim().min(1).max(200)}).strict();
const scope=(s:AuthSession):ResourceScope=>s.activeBranchId?{companyId:s.activeCompanyId!,branchId:s.activeBranchId}:s.activeCompanyId?{companyId:s.activeCompanyId}:{requireTenant:true};
export function registerAssetRoutes(app:FastifyInstance,service:AuthService){
 async function auth(req:FastifyRequest,reply:FastifyReply){const s=await service.session(req.cookies.vetoros_session);if(!s){reply.code(401).send({error:'unauthorized'});return;}if(!s.activeTenantId){reply.code(409).send({error:'tenant_required'});return;}return s;}
 async function allow(reply:FastifyReply,s:AuthSession,p:string){try{await requirePermission(service,s,p,scope(s));return true;}catch{reply.code(403).send({error:'forbidden'});return false;}}
 app.get('/assets',async(req,reply)=>{const q=list.safeParse(req.query);if(!q.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'customer_assets.read'))return;const term=q.data.search?`${q.data.search.toLowerCase()}%`:null,offset=(q.data.page-1)*q.data.pageSize;const rows=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`select a.*,c.legal_name as customer_name,count(*) over()::int as total from customer_assets a join customers c on c.id=a.customer_id where (${q.data.customerId??null}::uuid is null or a.customer_id=${q.data.customerId??null}) and (${q.data.category??null}::text is null or a.category=${q.data.category??null}) and (${q.data.status??null}::text is null or a.status=${q.data.status??null}) and (${term}::text is null or lower(c.legal_name) like ${term} or lower(a.brand) like ${term} or lower(a.model) like ${term} or lower(a.serial_number) like ${term} or lower(a.imei) like ${term} or lower(a.internal_identifier) like ${term} or exists(select 1 from customer_asset_identifiers i where i.asset_id=a.id and i.value_normalized like ${term})) order by a.created_at desc,a.id limit ${q.data.pageSize} offset ${offset}`));return{items:rows.map(r=>Object.fromEntries(Object.entries(r).filter(([key])=>key!=='total'))),page:q.data.page,pageSize:q.data.pageSize,total:Number(rows[0]?.total??0)};});
 app.get('/assets/:id',async(req,reply)=>{const p=params.safeParse(req.params);if(!p.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'customer_assets.read'))return;const row=await service.withAuthenticatedTenant(s,async tx=>{const [a]=await tx.execute(sql`select a.*,c.legal_name as customer_name from customer_assets a join customers c on c.id=a.customer_id where a.id=${p.data.id}`);if(!a)return null;const identifiers=await tx.execute(sql`select * from customer_asset_identifiers where asset_id=${p.data.id} order by identifier_type`);return{...a,identifiers};});return row??reply.code(404).send({error:'not_found'});});
 app.get('/customers/:id/assets',async(req,reply)=>{const p=params.safeParse(req.params);if(!p.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'customer_assets.read'))return;return service.withAuthenticatedTenant(s,tx=>tx.execute(sql`select * from customer_assets where customer_id=${p.data.id} order by created_at desc`));});
 app.post('/assets',async(req,reply)=>{const b=asset.safeParse(req.body);if(!b.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'customer_assets.create'))return;try{const row=await service.withAuthenticatedTenant(s,async tx=>{const customer=await tx.execute(sql`select id from customers where id=${b.data.customerId}`);if(!customer.length)return null;const [a]=await tx.execute(sql`insert into customer_assets(tenant_id,customer_id,internal_identifier,category,brand,model,serial_number,imei,asset_tag,description,notes,status,origin_company_id,origin_branch_id,created_by_identity_id,updated_by_identity_id) values(${s.activeTenantId!},${b.data.customerId},${b.data.internalIdentifier},${b.data.category},${b.data.brand??null},${b.data.model??null},${b.data.serialNumber??null},${b.data.imei??null},${b.data.assetTag??null},${b.data.description??null},${b.data.notes??null},${b.data.status},${b.data.originCompanyId??s.activeCompanyId},${b.data.originBranchId??s.activeBranchId},${s.identityId},${s.identityId}) returning *`);for(const item of b.data.identifiers??[])await tx.execute(sql`insert into customer_asset_identifiers(tenant_id,asset_id,identifier_type,value,value_normalized) values(${s.activeTenantId!},${a!.id},${item.identifierType},${item.value},${item.value.toLowerCase().replace(/\s/g,'')})`);return a!;});if(!row)return reply.code(404).send({error:'customer_not_found'});await service.auditResource(s,'customer_asset.created','customer_asset',String(row.id));return reply.code(201).send(row);}catch(e){if(typeof e==='object'&&e&&'cause'in e&&((e as {cause?:{code?:string}}).cause?.code==='23505'))return reply.code(409).send({error:'asset_identifier_already_exists'});throw e;}});
 app.patch('/assets/:id',async(req,reply)=>{const p=params.safeParse(req.params),b=update.safeParse(req.body);if(!p.success||!b.success||!Object.keys(b.data).length)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'customer_assets.update'))return;const [row]=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`update customer_assets set internal_identifier=coalesce(${b.data.internalIdentifier??null},internal_identifier),category=coalesce(${b.data.category??null},category),brand=case when ${'brand'in b.data} then ${b.data.brand??null} else brand end,model=case when ${'model'in b.data} then ${b.data.model??null} else model end,serial_number=case when ${'serialNumber'in b.data} then ${b.data.serialNumber??null} else serial_number end,imei=case when ${'imei'in b.data} then ${b.data.imei??null} else imei end,asset_tag=case when ${'assetTag'in b.data} then ${b.data.assetTag??null} else asset_tag end,description=case when ${'description'in b.data} then ${b.data.description??null} else description end,notes=case when ${'notes'in b.data} then ${b.data.notes??null} else notes end,status=coalesce(${b.data.status??null},status),updated_by_identity_id=${s.identityId},updated_at=now() where id=${p.data.id} returning *`));if(!row)return reply.code(404).send({error:'not_found'});await service.auditResource(s,'customer_asset.updated','customer_asset',p.data.id,{status:b.data.status});return row;});
 app.post('/assets/:id/identifiers',async(req,reply)=>{const p=params.safeParse(req.params),b=identifier.safeParse(req.body);if(!p.success||!b.success)return reply.code(400).send({error:'invalid_request'});const s=await auth(req,reply);if(!s||!await allow(reply,s,'customer_assets.update'))return;try{const [row]=await service.withAuthenticatedTenant(s,tx=>tx.execute(sql`insert into customer_asset_identifiers(tenant_id,asset_id,identifier_type,value,value_normalized) select ${s.activeTenantId!},a.id,${b.data.identifierType},${b.data.value},${b.data.value.toLowerCase().replace(/\s/g,'')} from customer_assets a where a.id=${p.data.id} returning *`));if(!row)return reply.code(404).send({error:'not_found'});await service.auditResource(s,'customer_asset.identifier.created','customer_asset',p.data.id,{identifierType:b.data.identifierType});return reply.code(201).send(row);}catch(e){if(typeof e==='object'&&e&&'cause'in e&&((e as {cause?:{code?:string}}).cause?.code==='23505'))return reply.code(409).send({error:'identifier_already_exists'});throw e;}});
}
